// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Project_Photo.Areas.PhotographerBooking;

public partial class Dispute
{
    public int DisputeId { get; set; }

    public int BookingId { get; set; }

    public string InitiatedBy { get; set; }

    public string DisputeType { get; set; }

    public string Description { get; set; }

    public string Evidence { get; set; }

    public string Status { get; set; }

    public long? UserId { get; set; }

    public string AdminNotes { get; set; }

    public string Resolution { get; set; }

    public DateTime CreatedAt { get; set; }

    public DateTime? ResolvedAt { get; set; }

    public virtual Booking Booking { get; set; }
}