// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Project_Photo.Areas.PhotographerBooking;

public partial class PhotographerService
{
    public int PhotographerServiceId { get; set; }

    public int PhotographerId { get; set; }

    public int ServiceTypeId { get; set; }

    public string ServiceName { get; set; }

    public string Description { get; set; }

    public decimal BasePrice { get; set; }

    public int Duration { get; set; }

    public int? MaxRevisions { get; set; }

    public int? DeliveryDays { get; set; }

    public int? IncludedPhotos { get; set; }

    public string AdditionalServices { get; set; }

    public bool IsActive { get; set; }

    public DateTime CreatedAt { get; set; }

    public virtual Photographer Photographer { get; set; }

    public virtual ServiceType ServiceType { get; set; }
}