// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Project_Photo.Areas.PhotographerBooking;

public partial class PhotographerVerificationHistory
{
    public int PhotographerVerificationHistoryId { get; set; }

    public int PhotographerId { get; set; }

    public string OldStatus { get; set; }

    public string NewStatus { get; set; }

    public string ActionType { get; set; }

    public long? ReviewedByUserId { get; set; }

    public string ReviewNotes { get; set; }

    public string RejectionReason { get; set; }

    public string RequiredDocuments { get; set; }

    public string SubmittedData { get; set; }

    public DateTime CreatedAt { get; set; }

    public virtual Photographer Photographer { get; set; }
}