// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Project_Photo.Areas.PhotographerBooking;

public partial class PhotographerSpecialty
{
    public int PhotographerSpecialtyId { get; set; }

    public int PhotographerId { get; set; }

    public int SpecialtyTagId { get; set; }

    public DateTime CreatedAt { get; set; }

    public virtual Photographer Photographer { get; set; }

    public virtual SpecialtyTag SpecialtyTag { get; set; }
}