// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Project_Photo.Areas.PhotographerBooking;

public partial class ServiceArea
{
    public int ServiceAreaId { get; set; }

    public int PhotographerId { get; set; }

    public string City { get; set; }

    public decimal? AdditionalFee { get; set; }

    public virtual Photographer Photographer { get; set; }
}