// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Project_Photo.Areas.PhotographerBooking;

public partial class SpecialtyTag
{
    public int SpecialtyTagId { get; set; }

    public string SpecialtyName { get; set; }

    public string Category { get; set; }

    public string Description { get; set; }

    public int DisplayOrder { get; set; }

    public bool IsActive { get; set; }

    public DateTime CreatedAt { get; set; }

    public virtual ICollection<PhotographerSpecialty> PhotographerSpecialties { get; set; } = new List<PhotographerSpecialty>();
}