// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;

namespace Project_Photo.Models;

public partial class AAContext : DbContext
{
    public AAContext(DbContextOptions<AAContext> options)
        : base(options)
    {
    }

    public virtual DbSet<BuyerAbnormal> BuyerAbnormals { get; set; }

    public virtual DbSet<BuyerCoupon> BuyerCoupons { get; set; }

    public virtual DbSet<BuyerDetail> BuyerDetails { get; set; }

    public virtual DbSet<BuyerFavoriteProduct> BuyerFavoriteProducts { get; set; }

    public virtual DbSet<ChatRoom> ChatRooms { get; set; }

    public virtual DbSet<Coupon> Coupons { get; set; }

    public virtual DbSet<FrequentlyAskedQuestion> FrequentlyAskedQuestions { get; set; }

    public virtual DbSet<Message> Messages { get; set; }

    public virtual DbSet<Order> Orders { get; set; }

    public virtual DbSet<OrderDetail> OrderDetails { get; set; }

    public virtual DbSet<OrderShipping> OrderShippings { get; set; }

    public virtual DbSet<PayoutBatch> PayoutBatchs { get; set; }

    public virtual DbSet<PayoutDetail> PayoutDetails { get; set; }

    public virtual DbSet<PickupConvenienceStore> PickupConvenienceStores { get; set; }

    public virtual DbSet<Product> Products { get; set; }

    public virtual DbSet<ProductAudit> ProductAudits { get; set; }

    public virtual DbSet<ProductImage> ProductImages { get; set; }

    public virtual DbSet<ProductProperty> ProductPropertys { get; set; }

    public virtual DbSet<ProductPropertyDetail> ProductPropertyDetails { get; set; }

    public virtual DbSet<ProductSellerCategoryMappin> ProductSellerCategoryMappins { get; set; }

    public virtual DbSet<ProductShippingOption> ProductShippingOptions { get; set; }

    public virtual DbSet<ProductSpecification> ProductSpecifications { get; set; }

    public virtual DbSet<ReceivingAddress> ReceivingAddresses { get; set; }

    public virtual DbSet<Report> Reports { get; set; }

    public virtual DbSet<Review> Reviews { get; set; }

    public virtual DbSet<ReviewPhoto> ReviewPhotos { get; set; }

    public virtual DbSet<SellerAuditHistory> SellerAuditHistories { get; set; }

    public virtual DbSet<SellerCategory> SellerCategories { get; set; }

    public virtual DbSet<SellerDetail> SellerDetails { get; set; }

    public virtual DbSet<ShoppingCart> ShoppingCarts { get; set; }

    public virtual DbSet<SpecOptionMapping> SpecOptionMappings { get; set; }

    public virtual DbSet<StoreBasicInformation> StoreBasicInformations { get; set; }

    public virtual DbSet<WalletTransaction> WalletTransactions { get; set; }

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        modelBuilder.Entity<BuyerAbnormal>(entity =>
        {
            entity.HasKey(e => e.BuyerAbnormalId).HasName("PK_BuyerAbnormalId");

            entity.ToTable("BuyerAbnormal", "Shopping");

            entity.Property(e => e.AbnormalType)
                .IsRequired()
                .HasMaxLength(50);
            entity.Property(e => e.CreatedAt)
                .HasDefaultValueSql("(getdate())")
                .HasAnnotation("Relational:DefaultConstraintName", "DF__BuyerAbno__Creat__33208881")
                .HasColumnType("datetime");
            entity.Property(e => e.HandlingResult).HasMaxLength(50);
            entity.Property(e => e.OccurrenceCount)
                .HasDefaultValue(1)
                .HasAnnotation("Relational:DefaultConstraintName", "DF__BuyerAbno__Occur__322C6448");
            entity.Property(e => e.UpdatedAt)
                .HasDefaultValueSql("(getdate())")
                .HasAnnotation("Relational:DefaultConstraintName", "DF__BuyerAbno__Updat__3414ACBA")
                .HasColumnType("datetime");
        });

        modelBuilder.Entity<BuyerCoupon>(entity =>
        {
            entity.ToTable("BuyerCoupons", "Shopping");

            entity.Property(e => e.CreatedAt).HasColumnType("datetime");
            entity.Property(e => e.ExpirationTime).HasColumnType("datetime");
            entity.Property(e => e.UpdatedAt).HasColumnType("datetime");

            entity.HasOne(d => d.Coupon).WithMany(p => p.BuyerCoupons)
                .HasForeignKey(d => d.CouponId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_BuyerCoupons_Coupons");
        });

        modelBuilder.Entity<BuyerDetail>(entity =>
        {
            entity.HasKey(e => e.BuyerDetailsId);

            entity.ToTable("BuyerDetails", "Shopping");

            entity.HasIndex(e => e.UserId, "IX_BuyerDetails_UserId");

            entity.Property(e => e.CreatedAt)
                .HasDefaultValueSql("(getdate())")
                .HasAnnotation("Relational:DefaultConstraintName", "DF__BuyerDeta__Creat__3F865F66")
                .HasColumnType("datetime");
            entity.Property(e => e.UpdatedAt)
                .HasDefaultValueSql("(getdate())")
                .HasAnnotation("Relational:DefaultConstraintName", "DF__BuyerDeta__Updat__407A839F")
                .HasColumnType("datetime");

            entity.HasOne(d => d.Address).WithMany(p => p.BuyerDetails)
                .HasForeignKey(d => d.AddressId)
                .HasConstraintName("FK_BuyerDetails_ReceivingAddresses");

            entity.HasOne(d => d.ConvenienceStore).WithMany(p => p.BuyerDetails)
                .HasForeignKey(d => d.ConvenienceStoreId)
                .HasConstraintName("FK_BuyerDetails_PickupConvenienceStores");
        });

        modelBuilder.Entity<BuyerFavoriteProduct>(entity =>
        {
            entity.HasKey(e => e.FavoriteProductId).HasName("PK_FavoriteProduct");

            entity.ToTable("BuyerFavoriteProducts", "Shopping");

            entity.HasIndex(e => e.ProductId, "IX_FavoriteProduct_ProductId");

            entity.HasIndex(e => e.UserId, "IX_FavoriteProduct_UserId");

            entity.HasIndex(e => new { e.UserId, e.ProductId }, "UQ_FavoriteProduct_UserProduct").IsUnique();

            entity.Property(e => e.CreatedAt)
                .HasDefaultValueSql("(getdate())")
                .HasAnnotation("Relational:DefaultConstraintName", "DF__FavoriteP__Creat__444B1483")
                .HasColumnType("datetime");
            entity.Property(e => e.UpdatedAt)
                .HasDefaultValueSql("(getdate())")
                .HasAnnotation("Relational:DefaultConstraintName", "DF__FavoriteP__Updat__453F38BC")
                .HasColumnType("datetime");

            entity.HasOne(d => d.User).WithMany(p => p.BuyerFavoriteProducts)
                .HasForeignKey(d => d.UserId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_BuyerFavoriteProducts_Products");
        });

        modelBuilder.Entity<ChatRoom>(entity =>
        {
            entity.HasKey(e => e.ChatRoomId).HasName("PK_ChatRoom");

            entity.ToTable("ChatRooms", "Shopping");

            entity.HasIndex(e => e.BuyerUserId, "IX_ChatRoom_BuyerUserId");

            entity.HasIndex(e => e.SellerUserId, "IX_ChatRoom_SellerUserId");

            entity.HasIndex(e => new { e.BuyerUserId, e.SellerUserId }, "UQ_ChatRoom_BuyerSeller").IsUnique();

            entity.Property(e => e.CreatedAt)
                .HasDefaultValueSql("(getdate())")
                .HasAnnotation("Relational:DefaultConstraintName", "DF__ChatRoom__Create__490FC9A0")
                .HasColumnType("datetime");
            entity.Property(e => e.UpdatedAt)
                .HasDefaultValueSql("(getdate())")
                .HasAnnotation("Relational:DefaultConstraintName", "DF__ChatRoom__Update__4A03EDD9")
                .HasColumnType("datetime");
        });

        modelBuilder.Entity<Coupon>(entity =>
        {
            entity.ToTable("Coupons", "Shopping");

            entity.Property(e => e.ActualUsageCount).HasAnnotation("Relational:DefaultConstraintName", "DF__Coupon__ActualUs__4F87BD05");
            entity.Property(e => e.Code)
                .IsRequired()
                .HasMaxLength(20);
            entity.Property(e => e.CouponName)
                .IsRequired()
                .HasMaxLength(50);
            entity.Property(e => e.CreatedAt)
                .HasDefaultValueSql("(getdate())")
                .HasAnnotation("Relational:DefaultConstraintName", "DF__Coupon__CreatedA__51700577")
                .HasColumnType("datetime");
            entity.Property(e => e.DisplaySetting)
                .IsRequired()
                .HasMaxLength(20);
            entity.Property(e => e.EffectiveDate).HasColumnType("datetime");
            entity.Property(e => e.ExpiryDate).HasColumnType("datetime");
            entity.Property(e => e.MinOrderAmount).HasColumnType("decimal(18, 2)");
            entity.Property(e => e.Type)
                .IsRequired()
                .HasMaxLength(20);
            entity.Property(e => e.UpdatedAt)
                .HasDefaultValueSql("(getdate())")
                .HasAnnotation("Relational:DefaultConstraintName", "DF__Coupon__UpdatedA__526429B0")
                .HasColumnType("datetime");
            entity.Property(e => e.Value).HasColumnType("decimal(18, 4)");
        });

        modelBuilder.Entity<FrequentlyAskedQuestion>(entity =>
        {
            entity.HasKey(e => e.FaqId).HasName("PK_Faq");

            entity.ToTable("FrequentlyAskedQuestions", "Shopping");

            entity.HasIndex(e => e.Category, "IX_Faq_Category");

            entity.HasIndex(e => e.SystemId, "IX_Faq_SystemId");

            entity.Property(e => e.Answer).IsRequired();
            entity.Property(e => e.Category)
                .IsRequired()
                .HasMaxLength(50);
            entity.Property(e => e.CreatedAt)
                .HasDefaultValueSql("(getdate())")
                .HasColumnType("datetime");
            entity.Property(e => e.Question)
                .IsRequired()
                .HasMaxLength(500);
            entity.Property(e => e.UpdatedAt)
                .HasDefaultValueSql("(getdate())")
                .HasColumnType("datetime");
        });

        modelBuilder.Entity<Message>(entity =>
        {
            entity.HasKey(e => e.MessageId).HasName("PK_Message");

            entity.ToTable("Messages", "Shopping");

            entity.Property(e => e.CreatedAt)
                .HasDefaultValueSql("(getdate())")
                .HasAnnotation("Relational:DefaultConstraintName", "DF__Message__Created__581D0306")
                .HasColumnType("datetime");
            entity.Property(e => e.IsRead).HasAnnotation("Relational:DefaultConstraintName", "DF__Message__IsRead__5728DECD");
            entity.Property(e => e.LinkDescription).HasMaxLength(500);
            entity.Property(e => e.LinkTitle).HasMaxLength(200);
            entity.Property(e => e.MediaUrl).HasMaxLength(500);
            entity.Property(e => e.MessageContent).HasMaxLength(500);
            entity.Property(e => e.MessageType)
                .IsRequired()
                .HasMaxLength(20)
                .HasDefaultValue("Text")
                .HasAnnotation("Relational:DefaultConstraintName", "DF__Message__Message__5540965B");
            entity.Property(e => e.SentAt)
                .HasDefaultValueSql("(getdate())")
                .HasAnnotation("Relational:DefaultConstraintName", "DF__Message__SentAt__5634BA94")
                .HasColumnType("datetime");
            entity.Property(e => e.ThumbnailUrl).HasMaxLength(500);
            entity.Property(e => e.UpdatedAt)
                .HasDefaultValueSql("(getdate())")
                .HasAnnotation("Relational:DefaultConstraintName", "DF__Message__Updated__5911273F")
                .HasColumnType("datetime");

            entity.HasOne(d => d.ChatRoom).WithMany(p => p.Messages)
                .HasForeignKey(d => d.ChatRoomId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_Messages_ChatRooms");

            entity.HasOne(d => d.Order).WithMany(p => p.Messages)
                .HasForeignKey(d => d.OrderId)
                .HasConstraintName("FK_Messages_Orders");

            entity.HasOne(d => d.Product).WithMany(p => p.Messages)
                .HasForeignKey(d => d.ProductId)
                .HasConstraintName("FK_Messages_Products");
        });

        modelBuilder.Entity<Order>(entity =>
        {
            entity.ToTable("Orders", "Shopping");

            entity.HasIndex(e => e.CreatedAt, "IX_Orders_CreatedAt").IsDescending();

            entity.HasIndex(e => e.OrderStatus, "IX_Orders_OrderStatus");

            entity.HasIndex(e => e.UserId, "IX_Orders_UserId");

            entity.Property(e => e.CreatedAt)
                .HasDefaultValueSql("(getdate())")
                .HasAnnotation("Relational:DefaultConstraintName", "DF__Orders__CreatedA__77CAB889")
                .HasColumnType("datetime");
            entity.Property(e => e.OrderStatus)
                .IsRequired()
                .HasMaxLength(20);
            entity.Property(e => e.PhoneNumber)
                .IsRequired()
                .HasMaxLength(20);
            entity.Property(e => e.RecipientName)
                .IsRequired()
                .HasMaxLength(50);
            entity.Property(e => e.ShippingAddress)
                .IsRequired()
                .HasMaxLength(200);
            entity.Property(e => e.ShippingMethod)
                .IsRequired()
                .HasMaxLength(20);
            entity.Property(e => e.TotalAmount).HasColumnType("decimal(18, 2)");
            entity.Property(e => e.UpdatedAt)
                .HasDefaultValueSql("(getdate())")
                .HasAnnotation("Relational:DefaultConstraintName", "DF__Orders__UpdatedA__78BEDCC2")
                .HasColumnType("datetime");
        });

        modelBuilder.Entity<OrderDetail>(entity =>
        {
            entity.HasKey(e => e.OrderDetailsId);

            entity.ToTable("OrderDetails", "Shopping");

            entity.HasIndex(e => e.OrderId, "IX_OrderDetails_OrderId");

            entity.HasIndex(e => e.SpecificationId, "IX_OrderDetails_SpecificationId");

            entity.Property(e => e.CreatedAt)
                .HasDefaultValueSql("(getdate())")
                .HasAnnotation("Relational:DefaultConstraintName", "DF__OrderDeta__Creat__711DBAFA")
                .HasColumnType("datetime");
            entity.Property(e => e.Quantity)
                .HasDefaultValue(1)
                .HasAnnotation("Relational:DefaultConstraintName", "DF__OrderDeta__Quant__702996C1");
            entity.Property(e => e.TransactionPrice).HasColumnType("decimal(18, 2)");
            entity.Property(e => e.UpdatedAt)
                .HasDefaultValueSql("(getdate())")
                .HasAnnotation("Relational:DefaultConstraintName", "DF__OrderDeta__Updat__7211DF33")
                .HasColumnType("datetime");

            entity.HasOne(d => d.Order).WithMany(p => p.OrderDetails)
                .HasForeignKey(d => d.OrderId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_OrderDetails_Orders");

            entity.HasOne(d => d.Specification).WithMany(p => p.OrderDetails)
                .HasForeignKey(d => d.SpecificationId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_OrderDetails_ProductSpecifications");
        });

        modelBuilder.Entity<OrderShipping>(entity =>
        {
            entity.HasKey(e => e.ShippingId);

            entity.ToTable("OrderShipping", "Shopping");

            entity.Property(e => e.CreatedAt)
                .HasDefaultValueSql("(getdate())")
                .HasColumnType("datetime");
            entity.Property(e => e.Freight).HasColumnType("decimal(18, 2)");
            entity.Property(e => e.LastApiSyncTime).HasColumnType("datetime");
            entity.Property(e => e.ReceivedTime).HasColumnType("datetime");
            entity.Property(e => e.ShipTime).HasColumnType("datetime");
            entity.Property(e => e.ShippingCostToSeller).HasColumnType("decimal(18, 2)");
            entity.Property(e => e.ShippingNumber).HasMaxLength(50);
            entity.Property(e => e.ShippingStatus)
                .IsRequired()
                .HasMaxLength(20)
                .HasDefaultValue("Pending");
            entity.Property(e => e.UpdatedAt)
                .HasDefaultValueSql("(getdate())")
                .HasColumnType("datetime");

            entity.HasOne(d => d.Order).WithMany(p => p.OrderShippings)
                .HasForeignKey(d => d.OrderId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_OrderShipping_Orders");
        });

        modelBuilder.Entity<PayoutBatch>(entity =>
        {
            entity.HasKey(e => e.PayoutBatchId).HasName("PK_PayoutBatch");

            entity.ToTable("PayoutBatchs", "Shopping");

            entity.Property(e => e.CreatedAt)
                .HasDefaultValueSql("(getdate())")
                .HasAnnotation("Relational:DefaultConstraintName", "DF__PayoutBat__Creat__68536ACF")
                .HasColumnType("datetime");
            entity.Property(e => e.Status)
                .IsRequired()
                .HasMaxLength(20);
            entity.Property(e => e.TotalCommissionFee)
                .HasAnnotation("Relational:DefaultConstraintName", "DF__PayoutBat__Total__6576FE24")
                .HasColumnType("decimal(18, 2)");
            entity.Property(e => e.TotalNetAmount)
                .HasAnnotation("Relational:DefaultConstraintName", "DF__PayoutBat__Total__675F4696")
                .HasColumnType("decimal(18, 2)");
            entity.Property(e => e.TotalPaymentProcessingFee)
                .HasAnnotation("Relational:DefaultConstraintName", "DF__PayoutBat__Total__666B225D")
                .HasColumnType("decimal(18, 2)");
            entity.Property(e => e.UpdatedAt)
                .HasDefaultValueSql("(getdate())")
                .HasAnnotation("Relational:DefaultConstraintName", "DF__PayoutBat__Updat__69478F08")
                .HasColumnType("datetime");
        });

        modelBuilder.Entity<PayoutDetail>(entity =>
        {
            entity.HasKey(e => e.PayoutDetailsId);

            entity.ToTable("PayoutDetails", "Shopping");

            entity.Property(e => e.CommissionFee).HasColumnType("decimal(18, 2)");
            entity.Property(e => e.CommissionRate).HasColumnType("decimal(18, 2)");
            entity.Property(e => e.CreatedAt)
                .HasDefaultValueSql("(getdate())")
                .HasColumnType("datetime");
            entity.Property(e => e.NetAmount).HasColumnType("decimal(18, 2)");
            entity.Property(e => e.OrderGrossAmount).HasColumnType("decimal(18, 2)");
            entity.Property(e => e.PaymentProcessingFee).HasColumnType("decimal(18, 2)");
            entity.Property(e => e.PaymentProcessingRate).HasColumnType("decimal(18, 2)");
            entity.Property(e => e.SettlementDate).HasColumnType("datetime");

            entity.HasOne(d => d.Order).WithMany(p => p.PayoutDetails)
                .HasForeignKey(d => d.OrderId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_PayoutDetails_Orders");

            entity.HasOne(d => d.PayoutBatch).WithMany(p => p.PayoutDetails)
                .HasForeignKey(d => d.PayoutBatchId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_PayoutDetails_PayoutBatchs");
        });

        modelBuilder.Entity<PickupConvenienceStore>(entity =>
        {
            entity.HasKey(e => e.ConvenienceStoreId).HasName("PK_ConvenienceStore");

            entity.ToTable("PickupConvenienceStores", "Shopping");

            entity.HasIndex(e => new { e.UserId, e.IsDefault }, "IX_ConvenienceStore_IsDefault");

            entity.HasIndex(e => e.UserId, "IX_ConvenienceStore_UserId");

            entity.Property(e => e.ConvenienceStoreCode)
                .IsRequired()
                .HasMaxLength(20);
            entity.Property(e => e.ConvenienceStoreName)
                .IsRequired()
                .HasMaxLength(100);
            entity.Property(e => e.CreatedAt)
                .HasDefaultValueSql("(getdate())")
                .HasAnnotation("Relational:DefaultConstraintName", "DF__Convenien__Creat__1466F737")
                .HasColumnType("datetime");
            entity.Property(e => e.IsDefault).HasAnnotation("Relational:DefaultConstraintName", "DF__Convenien__IsDef__1372D2FE");
            entity.Property(e => e.PhoneNumber)
                .IsRequired()
                .HasMaxLength(20);
            entity.Property(e => e.RecipientName)
                .IsRequired()
                .HasMaxLength(50);
            entity.Property(e => e.UpdatedAt)
                .HasDefaultValueSql("(getdate())")
                .HasAnnotation("Relational:DefaultConstraintName", "DF__Convenien__Updat__155B1B70")
                .HasColumnType("datetime");
        });

        modelBuilder.Entity<Product>(entity =>
        {
            entity.HasKey(e => e.ProductId).HasName("PK_Product");

            entity.ToTable("Products", "Shopping");

            entity.Property(e => e.AuditStatus)
                .IsRequired()
                .HasMaxLength(20);
            entity.Property(e => e.CreatedAt)
                .HasDefaultValueSql("(getdate())")
                .HasAnnotation("Relational:DefaultConstraintName", "DF__Product__Created__002AF460")
                .HasColumnType("datetime");
            entity.Property(e => e.ProductName)
                .IsRequired()
                .HasMaxLength(100);
            entity.Property(e => e.Status)
                .IsRequired()
                .HasMaxLength(20);
            entity.Property(e => e.UpdatedAt)
                .HasDefaultValueSql("(getdate())")
                .HasAnnotation("Relational:DefaultConstraintName", "DF__Product__Updated__011F1899")
                .HasColumnType("datetime");
        });

        modelBuilder.Entity<ProductAudit>(entity =>
        {
            entity.HasKey(e => e.ProductAuditId).HasName("PK_ProductAudit");

            entity.ToTable("ProductAudits", "Shopping");

            entity.Property(e => e.AuditTime)
                .HasDefaultValueSql("(getdate())")
                .HasAnnotation("Relational:DefaultConstraintName", "DF__ProductAu__Audit__6F00685E")
                .HasColumnType("datetime");
            entity.Property(e => e.CreatedAt)
                .HasDefaultValueSql("(getdate())")
                .HasAnnotation("Relational:DefaultConstraintName", "DF__ProductAu__Creat__6FF48C97")
                .HasColumnType("datetime");
            entity.Property(e => e.Status)
                .IsRequired()
                .HasMaxLength(20);
            entity.Property(e => e.UpdatedAt)
                .HasDefaultValueSql("(getdate())")
                .HasAnnotation("Relational:DefaultConstraintName", "DF__ProductAu__Updat__70E8B0D0")
                .HasColumnType("datetime");
            entity.Property(e => e.VerificationReasons).HasMaxLength(500);

            entity.HasOne(d => d.Product).WithMany(p => p.ProductAudits)
                .HasForeignKey(d => d.ProductId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_ProductAudits_Products");
        });

        modelBuilder.Entity<ProductImage>(entity =>
        {
            entity.HasKey(e => e.ProductImageId).HasName("PK_ProductImage");

            entity.ToTable("ProductImages", "Shopping");

            entity.Property(e => e.CreatedAt)
                .HasDefaultValueSql("(getdate())")
                .HasAnnotation("Relational:DefaultConstraintName", "DF__ProductIm__Creat__1A1FD08D")
                .HasColumnType("datetime");
            entity.Property(e => e.DisplayOrder).HasAnnotation("Relational:DefaultConstraintName", "DF__ProductIm__Displ__192BAC54");
            entity.Property(e => e.ImageUrl)
                .IsRequired()
                .HasMaxLength(500);
            entity.Property(e => e.IsMainImage).HasAnnotation("Relational:DefaultConstraintName", "DF__ProductIm__IsMai__1837881B");
            entity.Property(e => e.UpdatedAt)
                .HasDefaultValueSql("(getdate())")
                .HasAnnotation("Relational:DefaultConstraintName", "DF__ProductIm__Updat__1B13F4C6")
                .HasColumnType("datetime");

            entity.HasOne(d => d.Product).WithMany(p => p.ProductImages)
                .HasForeignKey(d => d.ProductId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_ProductImages_Products");
        });

        modelBuilder.Entity<ProductProperty>(entity =>
        {
            entity.HasKey(e => e.PropertyId).HasName("PK_Property");

            entity.ToTable("ProductPropertys", "Shopping");

            entity.Property(e => e.CreatedAt)
                .HasDefaultValueSql("(getdate())")
                .HasAnnotation("Relational:DefaultConstraintName", "DF__Property__Create__7C5A637C")
                .HasColumnType("datetime");
            entity.Property(e => e.PropertyName)
                .IsRequired()
                .HasMaxLength(50);
            entity.Property(e => e.UpdatedAt)
                .HasDefaultValueSql("(getdate())")
                .HasAnnotation("Relational:DefaultConstraintName", "DF__Property__Update__7D4E87B5")
                .HasColumnType("datetime");

            entity.HasOne(d => d.Product).WithMany(p => p.ProductProperties)
                .HasForeignKey(d => d.ProductId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_ProductPropertys_Products");
        });

        modelBuilder.Entity<ProductPropertyDetail>(entity =>
        {
            entity.HasKey(e => e.PropertyDetailsId).HasName("PK_PropertyDetails");

            entity.ToTable("ProductPropertyDetails", "Shopping");

            entity.Property(e => e.CreatedAt)
                .HasDefaultValueSql("(getdate())")
                .HasColumnType("datetime");
            entity.Property(e => e.OptionValue)
                .IsRequired()
                .HasMaxLength(50);
            entity.Property(e => e.UpdatedAt)
                .HasDefaultValueSql("(getdate())")
                .HasColumnType("datetime");

            entity.HasOne(d => d.Property).WithMany(p => p.ProductPropertyDetails)
                .HasForeignKey(d => d.PropertyId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_ProductPropertyDetails_ProductPropertys");
        });

        modelBuilder.Entity<ProductSellerCategoryMappin>(entity =>
        {
            entity.HasKey(e => e.CategoryMappingId).HasName("PK_ProductSellerCategoryMapping");

            entity.ToTable("ProductSellerCategoryMappin", "Shopping");

            entity.HasOne(d => d.Product).WithMany(p => p.ProductSellerCategoryMappins)
                .HasForeignKey(d => d.ProductId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_ProductSellerCategoryMappin_Products");

            entity.HasOne(d => d.SellerCategory).WithMany(p => p.ProductSellerCategoryMappins)
                .HasForeignKey(d => d.SellerCategoryId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_ProductSellerCategoryMappin_SellerCategories");
        });

        modelBuilder.Entity<ProductShippingOption>(entity =>
        {
            entity.HasKey(e => e.ShippingOptionId).HasName("PK_ShippingOption");

            entity.ToTable("ProductShippingOption", "Shopping");

            entity.Property(e => e.CombineRule).HasMaxLength(20);
            entity.Property(e => e.CreatedAt)
                .HasDefaultValueSql("(getdate())")
                .HasAnnotation("Relational:DefaultConstraintName", "DF__ShippingO__Creat__7968E838")
                .HasColumnType("datetime");
            entity.Property(e => e.Freight)
                .HasAnnotation("Relational:DefaultConstraintName", "DF__ShippingO__Freig__7874C3FF")
                .HasColumnType("decimal(18, 2)");
            entity.Property(e => e.ShippingMethod)
                .IsRequired()
                .HasMaxLength(20);
            entity.Property(e => e.UpdatedAt)
                .HasDefaultValueSql("(getdate())")
                .HasAnnotation("Relational:DefaultConstraintName", "DF__ShippingO__Updat__7A5D0C71")
                .HasColumnType("datetime");

            entity.HasOne(d => d.Product).WithMany(p => p.ProductShippingOptions)
                .HasForeignKey(d => d.ProductId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_ProductShippingOption_Products");
        });

        modelBuilder.Entity<ProductSpecification>(entity =>
        {
            entity.HasKey(e => e.SpecificationId).HasName("PK_Specification");

            entity.ToTable("ProductSpecifications", "Shopping");

            entity.Property(e => e.CreatedAt)
                .HasDefaultValueSql("(getdate())")
                .HasAnnotation("Relational:DefaultConstraintName", "DF__Specifica__Creat__310335E5")
                .HasColumnType("datetime");
            entity.Property(e => e.Price).HasColumnType("decimal(18, 2)");
            entity.Property(e => e.StockQuantity).HasAnnotation("Relational:DefaultConstraintName", "DF__Specifica__Stock__300F11AC");
            entity.Property(e => e.UpdatedAt)
                .HasDefaultValueSql("(getdate())")
                .HasAnnotation("Relational:DefaultConstraintName", "DF__Specifica__Updat__31F75A1E")
                .HasColumnType("datetime");

            entity.HasOne(d => d.Product).WithMany(p => p.ProductSpecifications)
                .HasForeignKey(d => d.ProductId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_ProductSpecifications_Products");
        });

        modelBuilder.Entity<ReceivingAddress>(entity =>
        {
            entity.HasKey(e => e.AddressId).HasName("PK_Address");

            entity.ToTable("ReceivingAddresses", "Shopping");

            entity.Property(e => e.CreatedAt)
                .HasDefaultValueSql("(getdate())")
                .HasAnnotation("Relational:DefaultConstraintName", "DF__Address__Created__37B03374")
                .HasColumnType("datetime");
            entity.Property(e => e.FullAddress)
                .IsRequired()
                .HasMaxLength(200);
            entity.Property(e => e.IsDefault).HasAnnotation("Relational:DefaultConstraintName", "DF__Address__IsDefau__36BC0F3B");
            entity.Property(e => e.PhoneNumber)
                .IsRequired()
                .HasMaxLength(20);
            entity.Property(e => e.RecipientName)
                .IsRequired()
                .HasMaxLength(50);
            entity.Property(e => e.UpdatedAt)
                .HasDefaultValueSql("(getdate())")
                .HasAnnotation("Relational:DefaultConstraintName", "DF__Address__Updated__38A457AD")
                .HasColumnType("datetime");
        });

        modelBuilder.Entity<Report>(entity =>
        {
            entity.HasKey(e => e.ReportId).HasName("PK_ProductReport");

            entity.ToTable("Reports", "Shopping");

            entity.Property(e => e.CreatedAt)
                .HasDefaultValueSql("(getdate())")
                .HasAnnotation("Relational:DefaultConstraintName", "DF__ProductRe__Creat__05CEBF1D")
                .HasColumnType("datetime");
            entity.Property(e => e.ReportType)
                .IsRequired()
                .HasMaxLength(20);
            entity.Property(e => e.ReportingReasons).IsRequired();
            entity.Property(e => e.Status)
                .IsRequired()
                .HasMaxLength(20);
            entity.Property(e => e.UpdatedAt)
                .HasDefaultValueSql("(getdate())")
                .HasAnnotation("Relational:DefaultConstraintName", "DF__ProductRe__Updat__06C2E356")
                .HasColumnType("datetime");

            entity.HasOne(d => d.ReportedProduct).WithMany(p => p.Reports)
                .HasForeignKey(d => d.ReportedProductId)
                .HasConstraintName("FK_Reports_Products");
        });

        modelBuilder.Entity<Review>(entity =>
        {
            entity.HasKey(e => e.ReviewId).HasName("PK_Review");

            entity.ToTable("Reviews", "Shopping");

            entity.HasIndex(e => new { e.OrderDetailsId, e.ReviewerUserId, e.ReviewType }, "UQ_Review_OrderReviewer").IsUnique();

            entity.Property(e => e.CreatedAt)
                .HasDefaultValueSql("(getdate())")
                .HasAnnotation("Relational:DefaultConstraintName", "DF__Review__CreatedA__422DC1E7")
                .HasColumnType("datetime");
            entity.Property(e => e.ReviewType)
                .IsRequired()
                .HasMaxLength(20);
            entity.Property(e => e.UpdatedAt)
                .HasDefaultValueSql("(getdate())")
                .HasAnnotation("Relational:DefaultConstraintName", "DF__Review__UpdatedA__4321E620")
                .HasColumnType("datetime");

            entity.HasOne(d => d.OrderDetails).WithMany(p => p.Reviews)
                .HasForeignKey(d => d.OrderDetailsId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_Reviews_OrderDetails");
        });

        modelBuilder.Entity<ReviewPhoto>(entity =>
        {
            entity.HasKey(e => e.ReviewPhotoId).HasName("PK_ReviewPhoto");

            entity.ToTable("ReviewPhotos", "Shopping");

            entity.Property(e => e.CreatedAt)
                .HasDefaultValueSql("(getdate())")
                .HasColumnType("datetime");
            entity.Property(e => e.ImageUrl)
                .IsRequired()
                .HasMaxLength(500);
            entity.Property(e => e.UpdatedAt)
                .HasDefaultValueSql("(getdate())")
                .HasColumnType("datetime");

            entity.HasOne(d => d.Review).WithMany(p => p.ReviewPhotos)
                .HasForeignKey(d => d.ReviewId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_ReviewPhotos_Reviews");
        });

        modelBuilder.Entity<SellerAuditHistory>(entity =>
        {
            entity.HasKey(e => e.SellerAuditId);

            entity.ToTable("SellerAuditHistory", "Shopping");

            entity.Property(e => e.AuditStatus)
                .IsRequired()
                .HasMaxLength(20);
            entity.Property(e => e.AuditTime)
                .HasDefaultValueSql("(getdate())")
                .HasColumnType("datetime");
            entity.Property(e => e.CreatedAt)
                .HasDefaultValueSql("(getdate())")
                .HasColumnType("datetime");
            entity.Property(e => e.VerificationReasons).HasMaxLength(500);
        });

        modelBuilder.Entity<SellerCategory>(entity =>
        {
            entity.HasKey(e => e.SellerCategoryId).HasName("PK_SellerCategory");

            entity.ToTable("SellerCategories", "Shopping");

            entity.Property(e => e.CategoryName)
                .IsRequired()
                .HasMaxLength(20);
            entity.Property(e => e.CreatedAt)
                .HasDefaultValueSql("(getdate())")
                .HasAnnotation("Relational:DefaultConstraintName", "DF__SellerCat__Creat__0B9CA70C")
                .HasColumnType("datetime");
            entity.Property(e => e.IsVisible)
                .HasDefaultValue(true)
                .HasAnnotation("Relational:DefaultConstraintName", "DF__SellerCat__IsVis__0AA882D3");
            entity.Property(e => e.UpdatedAt)
                .HasDefaultValueSql("(getdate())")
                .HasAnnotation("Relational:DefaultConstraintName", "DF__SellerCat__Updat__0C90CB45")
                .HasColumnType("datetime");
        });

        modelBuilder.Entity<SellerDetail>(entity =>
        {
            entity.HasKey(e => e.SellerDetailsId);

            entity.ToTable("SellerDetails", "Shopping");

            entity.Property(e => e.AuditTime).HasColumnType("datetime");
            entity.Property(e => e.CreatedAt).HasColumnType("datetime");
            entity.Property(e => e.IdcardImage)
                .IsRequired()
                .HasColumnName("IDCardImage");
            entity.Property(e => e.ReviewStatus).HasMaxLength(20);
            entity.Property(e => e.UpdatedAt).HasColumnType("datetime");
            entity.Property(e => e.VerificationReasons).HasMaxLength(500);
            entity.Property(e => e.WalletBalance)
                .HasAnnotation("Relational:DefaultConstraintName", "DF_SellerDetails_WalletBalance")
                .HasColumnType("decimal(18, 2)");
        });

        modelBuilder.Entity<ShoppingCart>(entity =>
        {
            entity.ToTable("ShoppingCart", "Shopping");

            entity.Property(e => e.CreatedAt)
                .HasDefaultValueSql("(getdate())")
                .HasAnnotation("Relational:DefaultConstraintName", "DF__ShoppingC__Creat__1431ED0D")
                .HasColumnType("datetime");
            entity.Property(e => e.Quantity)
                .HasDefaultValue(1)
                .HasAnnotation("Relational:DefaultConstraintName", "DF_ShoppingCart_Quantity");
            entity.Property(e => e.UpdatedAt)
                .HasDefaultValueSql("(getdate())")
                .HasAnnotation("Relational:DefaultConstraintName", "DF__ShoppingC__Updat__15261146")
                .HasColumnType("datetime");

            entity.HasOne(d => d.Specification).WithMany(p => p.ShoppingCarts)
                .HasForeignKey(d => d.SpecificationId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_ShoppingCart_ProductSpecifications");
        });

        modelBuilder.Entity<SpecOptionMapping>(entity =>
        {
            entity.ToTable("SpecOptionMapping", "Shopping");

            entity.HasOne(d => d.PropertyDetails).WithMany(p => p.SpecOptionMappings)
                .HasForeignKey(d => d.PropertyDetailsId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_SpecOptionMapping_ProductPropertyDetails");

            entity.HasOne(d => d.Specification).WithMany(p => p.SpecOptionMappings)
                .HasForeignKey(d => d.SpecificationId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_SpecOptionMapping_ProductSpecifications");
        });

        modelBuilder.Entity<StoreBasicInformation>(entity =>
        {
            entity.HasKey(e => e.StoreId).HasName("PK_StoreInformation");

            entity.ToTable("StoreBasicInformation", "Shopping");

            entity.Property(e => e.CreatedAt)
                .HasDefaultValueSql("(getdate())")
                .HasAnnotation("Relational:DefaultConstraintName", "DF__StoreInfo__Creat__1EAF7B80")
                .HasColumnType("datetime");
            entity.Property(e => e.StoreDescription).HasMaxLength(500);
            entity.Property(e => e.StoreImageUrl).HasMaxLength(500);
            entity.Property(e => e.StoreName)
                .IsRequired()
                .HasMaxLength(100);
            entity.Property(e => e.UpdatedAt)
                .HasDefaultValueSql("(getdate())")
                .HasAnnotation("Relational:DefaultConstraintName", "DF__StoreInfo__Updat__1FA39FB9")
                .HasColumnType("datetime");
        });

        modelBuilder.Entity<WalletTransaction>(entity =>
        {
            entity.HasKey(e => e.TransactionId).HasName("PK_WalletTransaction");

            entity.ToTable("WalletTransactions", "Shopping");

            entity.Property(e => e.Amount).HasColumnType("decimal(18, 2)");
            entity.Property(e => e.CreatedAt)
                .HasDefaultValueSql("(getdate())")
                .HasColumnType("datetime");
            entity.Property(e => e.CurrentBalance).HasColumnType("decimal(18, 2)");
            entity.Property(e => e.TransactionStatus)
                .IsRequired()
                .HasMaxLength(20);
            entity.Property(e => e.TransactionType)
                .IsRequired()
                .HasMaxLength(30);
            entity.Property(e => e.UpdatedAt)
                .HasDefaultValueSql("(getdate())")
                .HasColumnType("datetime");
        });

        OnModelCreatingPartial(modelBuilder);
    }

    partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
}