// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;

namespace Project_Photo.Models;

public partial class AAContext : DbContext
{
    public AAContext(DbContextOptions<AAContext> options)
        : base(options)
    {
    }

    public virtual DbSet<AdminAction> AdminActions { get; set; }

    public virtual DbSet<AvailableSlot> AvailableSlots { get; set; }

    public virtual DbSet<Booking> Bookings { get; set; }

    public virtual DbSet<Dispute> Disputes { get; set; }

    public virtual DbSet<FavoritePhotographer> FavoritePhotographers { get; set; }

    public virtual DbSet<Photographer> Photographers { get; set; }

    public virtual DbSet<PhotographerService> PhotographerServices { get; set; }

    public virtual DbSet<PhotographerSpecialty> PhotographerSpecialties { get; set; }

    public virtual DbSet<PhotographerVerificationHistory> PhotographerVerificationHistories { get; set; }

    public virtual DbSet<Review> Reviews { get; set; }

    public virtual DbSet<ServiceArea> ServiceAreas { get; set; }

    public virtual DbSet<ServiceType> ServiceTypes { get; set; }

    public virtual DbSet<SpecialtyTag> SpecialtyTags { get; set; }

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        modelBuilder.Entity<AdminAction>(entity =>
        {
            entity.HasKey(e => e.AdminActionId).HasName("PK_AdminAction");

            entity.ToTable("AdminActions", "PhotographerBooking");

            entity.Property(e => e.ActionDetail).HasMaxLength(500);
            entity.Property(e => e.ActionType)
                .IsRequired()
                .HasMaxLength(50);
            entity.Property(e => e.CreatedAt)
                .HasDefaultValueSql("(getdate())")
                .HasColumnType("datetime");
            entity.Property(e => e.Ipaddress)
                .HasMaxLength(50)
                .HasColumnName("IPAddress");
            entity.Property(e => e.TargetType).HasMaxLength(50);
        });

        modelBuilder.Entity<AvailableSlot>(entity =>
        {
            entity.HasKey(e => e.AvailableSlotId).HasName("PK_AvailableSlot");

            entity.ToTable("AvailableSlots", "PhotographerBooking");

            entity.Property(e => e.CreatedAt)
                .HasDefaultValueSql("(getdate())")
                .HasColumnType("datetime");

            entity.HasOne(d => d.Photographer).WithMany(p => p.AvailableSlots)
                .HasForeignKey(d => d.PhotographerId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_AvailableSlots_Photographers");
        });

        modelBuilder.Entity<Booking>(entity =>
        {
            entity.HasKey(e => e.BookingId).HasName("PK_Booking");

            entity.ToTable("Bookings", "PhotographerBooking");

            entity.Property(e => e.AdditionalFees).HasColumnType("decimal(10, 2)");
            entity.Property(e => e.BookingNumber)
                .IsRequired()
                .HasMaxLength(50);
            entity.Property(e => e.BookingStatus)
                .IsRequired()
                .HasMaxLength(20);
            entity.Property(e => e.CancellationReason).HasMaxLength(500);
            entity.Property(e => e.CancelledAt).HasColumnType("datetime");
            entity.Property(e => e.CancelledBy).HasMaxLength(20);
            entity.Property(e => e.CompletedAt).HasColumnType("datetime");
            entity.Property(e => e.CreatedAt)
                .HasDefaultValueSql("(getdate())")
                .HasAnnotation("Relational:DefaultConstraintName", "DF__Booking__Created__61074EC2")
                .HasColumnType("datetime");
            entity.Property(e => e.DepositAmount).HasColumnType("decimal(10, 2)");
            entity.Property(e => e.DepositPaidAt).HasColumnType("datetime");
            entity.Property(e => e.DiscountAmount).HasColumnType("decimal(10, 2)");
            entity.Property(e => e.FullPaymentAt).HasColumnType("datetime");
            entity.Property(e => e.Location).HasMaxLength(200);
            entity.Property(e => e.PaymentStatus)
                .IsRequired()
                .HasMaxLength(20);
            entity.Property(e => e.ServicePrice)
                .HasAnnotation("Relational:DefaultConstraintName", "DF__Booking__Service__5F1F0650")
                .HasColumnType("decimal(10, 2)");
            entity.Property(e => e.UpdatedAt)
                .HasDefaultValueSql("(getdate())")
                .HasAnnotation("Relational:DefaultConstraintName", "DF__Booking__Updated__61FB72FB")
                .HasColumnType("datetime");

            entity.HasOne(d => d.AvailableSlot).WithMany(p => p.Bookings)
                .HasForeignKey(d => d.AvailableSlotId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_Bookings_AvailableSlots");

            entity.HasOne(d => d.Photographer).WithMany(p => p.Bookings)
                .HasForeignKey(d => d.PhotographerId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_Bookings_Photographers");
        });

        modelBuilder.Entity<Dispute>(entity =>
        {
            entity.HasKey(e => e.DisputeId).HasName("PK_Dispute");

            entity.ToTable("Disputes", "PhotographerBooking");

            entity.Property(e => e.CreatedAt)
                .HasDefaultValueSql("(getdate())")
                .HasColumnType("datetime");
            entity.Property(e => e.Description).IsRequired();
            entity.Property(e => e.DisputeType)
                .IsRequired()
                .HasMaxLength(50);
            entity.Property(e => e.InitiatedBy)
                .IsRequired()
                .HasMaxLength(20);
            entity.Property(e => e.ResolvedAt).HasColumnType("datetime");
            entity.Property(e => e.Status)
                .IsRequired()
                .HasMaxLength(20);

            entity.HasOne(d => d.Booking).WithMany(p => p.Disputes)
                .HasForeignKey(d => d.BookingId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_Disputes_Bookings");
        });

        modelBuilder.Entity<FavoritePhotographer>(entity =>
        {
            entity.ToTable("FavoritePhotographers", "PhotographerBooking");

            entity.Property(e => e.CreatedAt)
                .HasDefaultValueSql("(getdate())")
                .HasColumnType("datetime");

            entity.HasOne(d => d.Photographer).WithMany(p => p.FavoritePhotographers)
                .HasForeignKey(d => d.PhotographerId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_FavoritePhotographers_Photographers");
        });

        modelBuilder.Entity<Photographer>(entity =>
        {
            entity.HasKey(e => e.PhotographerId).HasName("PK_Photographer");

            entity.ToTable("Photographers", "PhotographerBooking");

            entity.Property(e => e.ApprovedAt).HasColumnType("datetime");
            entity.Property(e => e.AverageRating).HasColumnType("decimal(3, 2)");
            entity.Property(e => e.Awards).HasMaxLength(500);
            entity.Property(e => e.BusinessAddress).HasMaxLength(200);
            entity.Property(e => e.CertificateUrl)
                .HasMaxLength(500)
                .HasColumnName("CertificateURL");
            entity.Property(e => e.CreatedAt)
                .HasDefaultValueSql("(getdate())")
                .HasColumnType("datetime");
            entity.Property(e => e.Description).HasMaxLength(500);
            entity.Property(e => e.DisplayName).HasMaxLength(100);
            entity.Property(e => e.FacebookUrl)
                .HasMaxLength(200)
                .HasColumnName("FacebookURL");
            entity.Property(e => e.IdcardUrl)
                .HasMaxLength(500)
                .HasColumnName("IDCardURL");
            entity.Property(e => e.InstagramUrl)
                .HasMaxLength(200)
                .HasColumnName("InstagramURL");
            entity.Property(e => e.IsActive).HasDefaultValue(true);
            entity.Property(e => e.OtherDocuments).HasMaxLength(500);
            entity.Property(e => e.PortfolioUrl)
                .HasMaxLength(500)
                .HasColumnName("PortfolioURL");
            entity.Property(e => e.RejectionReason).HasMaxLength(500);
            entity.Property(e => e.StudioName)
                .IsRequired()
                .HasMaxLength(100);
            entity.Property(e => e.StudioType)
                .IsRequired()
                .HasMaxLength(20);
            entity.Property(e => e.SuspendedAt).HasColumnType("datetime");
            entity.Property(e => e.SuspendedReason).HasMaxLength(500);
            entity.Property(e => e.UpdatedAt)
                .HasDefaultValueSql("(getdate())")
                .HasColumnType("datetime");
            entity.Property(e => e.VerificationDate).HasColumnType("datetime");
            entity.Property(e => e.VerificationStatus)
                .IsRequired()
                .HasMaxLength(20);
            entity.Property(e => e.WebsiteUrl)
                .HasMaxLength(200)
                .HasColumnName("WebsiteURL");
        });

        modelBuilder.Entity<PhotographerService>(entity =>
        {
            entity.HasKey(e => e.PhotographerServiceId).HasName("PK_PhotographerService");

            entity.ToTable("PhotographerServices", "PhotographerBooking");

            entity.Property(e => e.AdditionalServices).HasMaxLength(500);
            entity.Property(e => e.BasePrice).HasColumnType("decimal(10, 2)");
            entity.Property(e => e.CreatedAt)
                .HasDefaultValueSql("(getdate())")
                .HasColumnType("datetime");
            entity.Property(e => e.Description).HasMaxLength(500);
            entity.Property(e => e.IsActive).HasDefaultValue(true);
            entity.Property(e => e.ServiceName)
                .IsRequired()
                .HasMaxLength(100);

            entity.HasOne(d => d.Photographer).WithMany(p => p.PhotographerServices)
                .HasForeignKey(d => d.PhotographerId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_PhotographerServices_Photographers");

            entity.HasOne(d => d.ServiceType).WithMany(p => p.PhotographerServices)
                .HasForeignKey(d => d.ServiceTypeId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_PhotographerServices_ServiceTypes");
        });

        modelBuilder.Entity<PhotographerSpecialty>(entity =>
        {
            entity.ToTable("PhotographerSpecialties", "PhotographerBooking");

            entity.Property(e => e.CreatedAt)
                .HasDefaultValueSql("(getdate())")
                .HasColumnType("datetime");

            entity.HasOne(d => d.Photographer).WithMany(p => p.PhotographerSpecialties)
                .HasForeignKey(d => d.PhotographerId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_PhotographerSpecialties_Photographers");

            entity.HasOne(d => d.SpecialtyTag).WithMany(p => p.PhotographerSpecialties)
                .HasForeignKey(d => d.SpecialtyTagId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_PhotographerSpecialties_SpecialtyTags");
        });

        modelBuilder.Entity<PhotographerVerificationHistory>(entity =>
        {
            entity.ToTable("PhotographerVerificationHistory", "PhotographerBooking");

            entity.Property(e => e.ActionType)
                .IsRequired()
                .HasMaxLength(50);
            entity.Property(e => e.CreatedAt)
                .HasDefaultValueSql("(getdate())")
                .HasColumnType("datetime");
            entity.Property(e => e.NewStatus)
                .IsRequired()
                .HasMaxLength(20);
            entity.Property(e => e.OldStatus).HasMaxLength(20);
            entity.Property(e => e.RejectionReason).HasMaxLength(500);
            entity.Property(e => e.RequiredDocuments).HasMaxLength(500);
            entity.Property(e => e.ReviewNotes).HasMaxLength(500);
            entity.Property(e => e.SubmittedData).HasMaxLength(500);

            entity.HasOne(d => d.Photographer).WithMany(p => p.PhotographerVerificationHistories)
                .HasForeignKey(d => d.PhotographerId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_PhotographerVerificationHistory_Photographers");
        });

        modelBuilder.Entity<Review>(entity =>
        {
            entity.HasKey(e => e.ReviewId).HasName("PK_Review");

            entity.ToTable("Reviews", "PhotographerBooking");

            entity.Property(e => e.CreatedAt)
                .HasDefaultValueSql("(getdate())")
                .HasColumnType("datetime");
            entity.Property(e => e.RepliedAt).HasColumnType("datetime");
            entity.Property(e => e.ReviewContent).HasMaxLength(500);
            entity.Property(e => e.ReviewTitle).HasMaxLength(100);

            entity.HasOne(d => d.Booking).WithMany(p => p.Reviews)
                .HasForeignKey(d => d.BookingId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_Reviews_Bookings");

            entity.HasOne(d => d.Photographer).WithMany(p => p.Reviews)
                .HasForeignKey(d => d.PhotographerId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_Reviews_Photographers");
        });

        modelBuilder.Entity<ServiceArea>(entity =>
        {
            entity.HasKey(e => e.ServiceAreaId).HasName("PK_ServiceArea");

            entity.ToTable("ServiceAreas", "PhotographerBooking");

            entity.Property(e => e.AdditionalFee).HasColumnType("decimal(10, 2)");
            entity.Property(e => e.City)
                .IsRequired()
                .HasMaxLength(50);

            entity.HasOne(d => d.Photographer).WithMany(p => p.ServiceAreas)
                .HasForeignKey(d => d.PhotographerId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_ServiceAreas_Photographers");
        });

        modelBuilder.Entity<ServiceType>(entity =>
        {
            entity.HasKey(e => e.ServiceTypeId).HasName("PK_ServiceType");

            entity.ToTable("ServiceTypes", "PhotographerBooking");

            entity.Property(e => e.Description).HasMaxLength(200);
            entity.Property(e => e.IconUrl)
                .HasMaxLength(200)
                .HasColumnName("IconURL");
            entity.Property(e => e.IsActive).HasDefaultValue(true);
            entity.Property(e => e.ServiceName)
                .IsRequired()
                .HasMaxLength(50);
        });

        modelBuilder.Entity<SpecialtyTag>(entity =>
        {
            entity.HasKey(e => e.SpecialtyTagId).HasName("PK_SpecialtyTag");

            entity.ToTable("SpecialtyTags", "PhotographerBooking");

            entity.Property(e => e.Category).HasMaxLength(50);
            entity.Property(e => e.CreatedAt)
                .HasDefaultValueSql("(getdate())")
                .HasColumnType("datetime");
            entity.Property(e => e.Description).HasMaxLength(200);
            entity.Property(e => e.IsActive).HasDefaultValue(true);
            entity.Property(e => e.SpecialtyName)
                .IsRequired()
                .HasMaxLength(50);
        });

        OnModelCreatingPartial(modelBuilder);
    }

    partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
}