// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Project_Photo.Models;

public partial class AdminAction1
{
    public int ActionId { get; set; }

    public int ReportId { get; set; }

    public long AdminId { get; set; }

    public string ReviewResults { get; set; }

    public string Details { get; set; }

    public DateTime CreatedAt { get; set; }

    public DateTime UpdateAt { get; set; }

    public virtual Report1 Report { get; set; }
}