// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Project_Photo.Models;

public partial class AdminAction
{
    public int AdminActionId { get; set; }

    public long UserId { get; set; }

    public string ActionType { get; set; }

    public string TargetType { get; set; }

    public int? TargetId { get; set; }

    public string ActionDetail { get; set; }

    public string Ipaddress { get; set; }

    public DateTime CreatedAt { get; set; }

    public virtual User User { get; set; }
}