// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Project_Photo.Models;

public partial class BankBranch
{
    public int BranchId { get; set; }

    public int BankId { get; set; }

    public string BranchCode { get; set; }

    public string BranchName { get; set; }

    public string City { get; set; }

    public string District { get; set; }

    public bool IsActive { get; set; }

    public DateTime CreatedAt { get; set; }

    public DateTime UpdatedAt { get; set; }

    public virtual Bank Bank { get; set; }

    public virtual ICollection<UserBankAccount> UserBankAccounts { get; set; } = new List<UserBankAccount>();
}