// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Project_Photo.Models;

public partial class Booking
{
    public int BookingId { get; set; }

    public string BookingNumber { get; set; }

    public long UserId { get; set; }

    public long PaymentMethodId { get; set; }

    public int AvailableSlotId { get; set; }

    public int PhotographerId { get; set; }

    public int PhotographerServiceId { get; set; }

    public DateOnly BookingDate { get; set; }

    public TimeOnly BookingStartTime { get; set; }

    public TimeOnly BookingEndTime { get; set; }

    public string Location { get; set; }

    public decimal ServicePrice { get; set; }

    public decimal? AdditionalFees { get; set; }

    public decimal? DiscountAmount { get; set; }

    public string BookingStatus { get; set; }

    public string PaymentStatus { get; set; }

    public decimal? DepositAmount { get; set; }

    public DateTime? DepositPaidAt { get; set; }

    public DateTime? FullPaymentAt { get; set; }

    public string CustomerNotes { get; set; }

    public string PhotographerNotes { get; set; }

    public string CancellationReason { get; set; }

    public string CancelledBy { get; set; }

    public DateTime? CancelledAt { get; set; }

    public DateTime CreatedAt { get; set; }

    public DateTime UpdatedAt { get; set; }

    public DateTime? CompletedAt { get; set; }

    public virtual AvailableSlot AvailableSlot { get; set; }

    public virtual ICollection<Dispute> Disputes { get; set; } = new List<Dispute>();

    public virtual Photographer Photographer { get; set; }

    public virtual ICollection<Review> Reviews { get; set; } = new List<Review>();
}