// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Project_Photo.Models;

public partial class BuyerAbnormal
{
    public int BuyerAbnormalId { get; set; }

    public long UserId { get; set; }

    public string AbnormalType { get; set; }

    public int OccurrenceCount { get; set; }

    public string HandlingResult { get; set; }

    public DateTime CreatedAt { get; set; }

    public DateTime UpdatedAt { get; set; }
}