// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Project_Photo.Models;

public partial class ChatMember
{
    public int RoomId { get; set; }

    public long UserId { get; set; }

    public DateTime JoinAt { get; set; }

    public DateTime? LeaveAt { get; set; }

    public virtual ChatRoom1 Room { get; set; }

    public virtual User User { get; set; }
}