// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Project_Photo.Models;

public partial class CommentLike
{
    public long UserId { get; set; }

    public int CommentId { get; set; }

    public DateTime CreatedAt { get; set; }

    public virtual Comment Comment { get; set; }

    public virtual User User { get; set; }
}