// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Project_Photo.Models;

public partial class Coupon
{
    public int CouponId { get; set; }

    public long? PublisherUserId { get; set; }

    public string CouponName { get; set; }

    public string Code { get; set; }

    public string Type { get; set; }

    public decimal? MinOrderAmount { get; set; }

    public decimal Value { get; set; }

    public int? MaxTotalUsage { get; set; }

    public int ActualUsageCount { get; set; }

    public int? MaxPerUserClaim { get; set; }

    public string DisplaySetting { get; set; }

    public DateTime CreatedAt { get; set; }

    public DateTime EffectiveDate { get; set; }

    public DateTime ExpiryDate { get; set; }

    public DateTime UpdatedAt { get; set; }

    public virtual ICollection<BuyerCoupon> BuyerCoupons { get; set; } = new List<BuyerCoupon>();

    public virtual User PublisherUser { get; set; }
}