// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Project_Photo.Models;

public partial class EventMember
{
    public int EventId { get; set; }

    public long UserId { get; set; }

    public string Status { get; set; }

    public DateTime JoinAt { get; set; }

    public DateTime UpdateAt { get; set; }

    public DateTime? LeftAt { get; set; }

    public virtual Event Event { get; set; }

    public virtual User User { get; set; }
}