// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Project_Photo.Models;

public partial class FavoritePhotographer
{
    public int FavoritePhotographerId { get; set; }

    public long UserId { get; set; }

    public int PhotographerId { get; set; }

    public DateTime CreatedAt { get; set; }

    public virtual Photographer Photographer { get; set; }
}