// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Project_Photo.Models;

public partial class Follow
{
    public long FollowerId { get; set; }

    public long FollowingId { get; set; }

    public DateTime CreatedAt { get; set; }

    public DateTime? DeleteAt { get; set; }

    public virtual User Follower { get; set; }

    public virtual User Following { get; set; }
}