// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Project_Photo.Models;

public partial class Following
{
    public long UserId { get; set; }

    public long ChannelId { get; set; }

    public DateTime CreatedAt { get; set; }

    public virtual Channel Channel { get; set; }

    public virtual User User { get; set; }
}