// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Project_Photo.Models;

public partial class FrequentlyAskedQuestion
{
    public int FaqId { get; set; }

    public int SystemId { get; set; }

    public string Category { get; set; }

    public string Question { get; set; }

    public string Answer { get; set; }

    public DateTime CreatedAt { get; set; }

    public DateTime UpdatedAt { get; set; }
}