// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Project_Photo.Models;

public partial class Invoice
{
    public long InvoiceId { get; set; }

    public long UserId { get; set; }

    public long TransactionId { get; set; }

    public string InvoiceNumber { get; set; }

    public DateOnly InvoiceDate { get; set; }

    public string InvoiceType { get; set; }

    public string SellerName { get; set; }

    public string SellerTaxId { get; set; }

    public string SellerAddress { get; set; }

    public int? CompanyBankId { get; set; }

    public string CompanyBankAccountNumber { get; set; }

    public string BuyerName { get; set; }

    public string BuyerTaxId { get; set; }

    public string BuyerAddress { get; set; }

    public string CarrierType { get; set; }

    public string CarrierNumber { get; set; }

    public decimal TotalAmount { get; set; }

    public decimal TaxAmount { get; set; }

    public string RandomCode { get; set; }

    public string QrcodeLeft { get; set; }

    public string QrcodeRight { get; set; }

    public string InvoiceStatus { get; set; }

    public DateTime? VoidedAt { get; set; }

    public string VoidReason { get; set; }

    public DateTime CreatedAt { get; set; }

    public DateTime UpdatedAt { get; set; }

    public virtual PaymentTransaction Transaction { get; set; }

    public virtual User User { get; set; }
}