// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Project_Photo.Models;

public partial class InvoiceSetting
{
    public long InvoiceSettingId { get; set; }

    public long UserId { get; set; }

    public bool InvoiceType { get; set; }

    public string CarrierType { get; set; }

    public string CarrierNumber { get; set; }

    public string CompanyName { get; set; }

    public string TaxId { get; set; }

    public string CompanyAddress { get; set; }

    public DateTime CreatedAt { get; set; }

    public DateTime UpdatedAt { get; set; }

    public virtual User User { get; set; }
}