// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Project_Photo.Models;

public partial class Message
{
    public int MessageId { get; set; }

    public int ChatRoomId { get; set; }

    public long SenderUserId { get; set; }

    public string MessageType { get; set; }

    public string MessageContent { get; set; }

    public string MediaUrl { get; set; }

    public string ThumbnailUrl { get; set; }

    public int? StickerId { get; set; }

    public long? ProductId { get; set; }

    public int? OrderId { get; set; }

    public string LinkTitle { get; set; }

    public string LinkDescription { get; set; }

    public DateTime SentAt { get; set; }

    public bool IsRead { get; set; }

    public DateTime CreatedAt { get; set; }

    public DateTime UpdatedAt { get; set; }

    public virtual ChatRoom ChatRoom { get; set; }

    public virtual Order Order { get; set; }

    public virtual Product Product { get; set; }

    public virtual User SenderUser { get; set; }
}