// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Project_Photo.Models;

public partial class Message1
{
    public int MessageId { get; set; }

    public int RoomId { get; set; }

    public long SenderId { get; set; }

    public string MessageContent { get; set; }

    public string MessageType { get; set; }

    public int? StickerId { get; set; }

    public DateTime? LastReadAt { get; set; }

    public DateTime CreatedAt { get; set; }

    public DateTime? DeletedAt { get; set; }

    public virtual ChatRoom1 Room { get; set; }

    public virtual User Sender { get; set; }

    public virtual Sticker Sticker { get; set; }
}