// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Project_Photo.Models;

public partial class NotificationSchedule
{
    public long ScheduleId { get; set; }

    public int TemplateId { get; set; }

    public string TargetUserIds { get; set; }

    public int? TargetRoleId { get; set; }

    public DateTime ScheduledTime { get; set; }

    public string RecurringRule { get; set; }

    public int Status { get; set; }

    public DateTime? SentAt { get; set; }

    public long CreatedBy { get; set; }

    public DateTime CreatedAt { get; set; }

    public DateTime UpdatedAt { get; set; }

    public virtual NotificationTemplate Template { get; set; }
}