// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Project_Photo.Models;

public partial class NotificationTemplate
{
    public int TemplateId { get; set; }

    public string TemplateCode { get; set; }

    public string TemplateName { get; set; }

    public int CategoryId { get; set; }

    public int SystemId { get; set; }

    public string Subject { get; set; }

    public string ContentTemplate { get; set; }

    public string Variables { get; set; }

    public bool IsActive { get; set; }

    public DateTime CreatedAt { get; set; }

    public DateTime UpdatedAt { get; set; }

    public virtual ICollection<NotificationSchedule> NotificationSchedules { get; set; } = new List<NotificationSchedule>();

    public virtual ICollection<Notification> Notifications { get; set; } = new List<Notification>();
}