// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Project_Photo.Models;

public partial class Notification
{
    public long NotificationId { get; set; }

    public int? TemplateId { get; set; }

    public int CategoryId { get; set; }

    public int PriorityId { get; set; }

    public string NotificationTitle { get; set; }

    public string NotificationContent { get; set; }

    public string ActionUrl { get; set; }

    public string RelatedObjectType { get; set; }

    public long? RelatedObjectId { get; set; }

    public int CreatedBy { get; set; }

    public DateTime CreatedAt { get; set; }

    public virtual NotificationCategory Category { get; set; }

    public virtual ICollection<NotificationRecipient> NotificationRecipients { get; set; } = new List<NotificationRecipient>();

    public virtual NotificationPriority Priority { get; set; }

    public virtual NotificationTemplate Template { get; set; }
}