// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Project_Photo.Models;

public partial class Notification1
{
    public int NotificationId { get; set; }

    public long UserId { get; set; }

    public string Title { get; set; }

    public string NotificationsContent { get; set; }

    public bool IsRead { get; set; }

    public DateTime CreatedAt { get; set; }

    public DateTime UpdateAt { get; set; }

    public virtual User User { get; set; }
}