// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Project_Photo.Models;

public partial class NotificationDelivery
{
    public long DeliveryId { get; set; }

    public long RecipientId { get; set; }

    public int ChannelTypeId { get; set; }

    public int DeliveryStatusId { get; set; }

    public string RecipientAddress { get; set; }

    public DateTime? SentAt { get; set; }

    public DateTime? DeliveredAt { get; set; }

    public string ErrorCode { get; set; }

    public string ErrorMessage { get; set; }

    public int RetryCount { get; set; }

    public DateTime CreatedAt { get; set; }

    public DateTime UpdatedAt { get; set; }

    public virtual NotificationChannelType ChannelType { get; set; }

    public virtual NotificationDeliveryStatus DeliveryStatus { get; set; }

    public virtual NotificationRecipient Recipient { get; set; }
}