// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Project_Photo.Models;

public partial class Order
{
    public int OrderId { get; set; }

    public long UserId { get; set; }

    public string OrderStatus { get; set; }

    public decimal TotalAmount { get; set; }

    public int? SellerCouponId { get; set; }

    public int? PlatformCouponId { get; set; }

    public string RecipientName { get; set; }

    public string PhoneNumber { get; set; }

    public string ShippingAddress { get; set; }

    public string ShippingMethod { get; set; }

    public DateTime CreatedAt { get; set; }

    public DateTime UpdatedAt { get; set; }

    public virtual ICollection<Message> Messages { get; set; } = new List<Message>();

    public virtual ICollection<OrderDetail> OrderDetails { get; set; } = new List<OrderDetail>();

    public virtual ICollection<OrderShipping> OrderShippings { get; set; } = new List<OrderShipping>();

    public virtual ICollection<PayoutDetail> PayoutDetails { get; set; } = new List<PayoutDetail>();
}