// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Project_Photo.Models;

public partial class OrderShipping
{
    public int ShippingId { get; set; }

    public int OrderId { get; set; }

    public string ShippingNumber { get; set; }

    public decimal Freight { get; set; }

    public decimal? ShippingCostToSeller { get; set; }

    public string ShippingStatus { get; set; }

    public DateTime? ShipTime { get; set; }

    public DateTime? ReceivedTime { get; set; }

    public DateTime? LastApiSyncTime { get; set; }

    public DateTime CreatedAt { get; set; }

    public DateTime UpdatedAt { get; set; }

    public virtual Order Order { get; set; }
}