// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Project_Photo.Models;

public partial class PaymentMethod
{
    public long PaymentMethodId { get; set; }

    public long UserId { get; set; }

    public int PaymentMethodTypeId { get; set; }

    public int? BankId { get; set; }

    public int? CardBrandId { get; set; }

    public string CardToken { get; set; }

    public string CardLast4 { get; set; }

    public string CardholderName { get; set; }

    public int? ExpiryMonth { get; set; }

    public int? ExpiryYear { get; set; }

    public long? BankAccountId { get; set; }

    public bool IsDefault { get; set; }

    public bool IsActive { get; set; }

    public DateTime? VerifiedAt { get; set; }

    public DateTime CreatedAt { get; set; }

    public DateTime UpdatedAt { get; set; }

    public virtual Bank Bank { get; set; }

    public virtual CardBrand CardBrand { get; set; }

    public virtual PaymentMethodType PaymentMethodType { get; set; }

    public virtual ICollection<PaymentTransaction> PaymentTransactions { get; set; } = new List<PaymentTransaction>();

    public virtual User User { get; set; }
}