// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Project_Photo.Models;

public partial class PaymentTransaction
{
    public long TransactionId { get; set; }

    public long UserId { get; set; }

    public long? SubscriptionId { get; set; }

    public long PaymentMethodId { get; set; }

    public int TransactionTypeId { get; set; }

    public string TransactionNo { get; set; }

    public decimal Amount { get; set; }

    public string Currency { get; set; }

    public string Description { get; set; }

    public string MerchantTradeNo { get; set; }

    public string GatewayTransactionId { get; set; }

    public string GatewayName { get; set; }

    public DateTime CreatedAt { get; set; }

    public virtual ICollection<Invoice> Invoices { get; set; } = new List<Invoice>();

    public virtual PaymentMethod PaymentMethod { get; set; }

    public virtual ICollection<RefundRequest> RefundRequests { get; set; } = new List<RefundRequest>();

    public virtual ICollection<TransactionStatusLog> TransactionStatusLogs { get; set; } = new List<TransactionStatusLog>();

    public virtual TransactionType TransactionType { get; set; }

    public virtual User User { get; set; }
}