// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Project_Photo.Models;

public partial class PayoutBatch
{
    public int PayoutBatchId { get; set; }

    public long UserId { get; set; }

    public long BankAccountId { get; set; }

    public DateOnly StartDate { get; set; }

    public DateOnly EndDate { get; set; }

    public decimal TotalCommissionFee { get; set; }

    public decimal TotalPaymentProcessingFee { get; set; }

    public decimal TotalNetAmount { get; set; }

    public string Status { get; set; }

    public DateTime CreatedAt { get; set; }

    public DateTime UpdatedAt { get; set; }

    public virtual ICollection<PayoutDetail> PayoutDetails { get; set; } = new List<PayoutDetail>();
}