// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Project_Photo.Models;

public partial class PayoutDetail
{
    public int PayoutDetailsId { get; set; }

    public int PayoutBatchId { get; set; }

    public int OrderId { get; set; }

    public decimal OrderGrossAmount { get; set; }

    public decimal CommissionRate { get; set; }

    public decimal CommissionFee { get; set; }

    public decimal PaymentProcessingRate { get; set; }

    public decimal PaymentProcessingFee { get; set; }

    public decimal NetAmount { get; set; }

    public DateTime? SettlementDate { get; set; }

    public DateTime CreatedAt { get; set; }

    public virtual Order Order { get; set; }

    public virtual PayoutBatch PayoutBatch { get; set; }
}