// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Project_Photo.Models;

public partial class PhotoLocation
{
    public long LocationId { get; set; }

    public long PhotoId { get; set; }

    public int SourceId { get; set; }

    public string Country { get; set; }

    public string City { get; set; }

    public string District { get; set; }

    public string PlaceName { get; set; }

    public string Address { get; set; }

    public decimal? Latitude { get; set; }

    public decimal? Longitude { get; set; }

    public long? SetBy { get; set; }

    public DateTime CreatedAt { get; set; }

    public DateTime UpdatedAt { get; set; }

    public virtual Photo Photo { get; set; }

    public virtual PhotoClassificationSource Source { get; set; }
}