// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Project_Photo.Models;

public partial class PhotoPhotoTag
{
    public long PhotoTagId { get; set; }

    public long PhotoId { get; set; }

    public int TagId { get; set; }

    public int SourceId { get; set; }

    public decimal? Confidence { get; set; }

    public long? AddedBy { get; set; }

    public DateTime AddedAt { get; set; }

    public DateTime CreatedAt { get; set; }

    public virtual Photo Photo { get; set; }

    public virtual PhotoTag Tag { get; set; }
}