// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Project_Photo.Models;

public partial class PhotoFeatureToggle
{
    public int FeaturedId { get; set; }

    public string FeatureCode { get; set; }

    public string FeatureName { get; set; }

    public string Description { get; set; }

    public bool IsEnabled { get; set; }

    public string Category { get; set; }

    public DateTime CreatedAt { get; set; }

    public DateTime UpdatedAt { get; set; }
}