// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Project_Photo.Models;

public partial class PhotoCategory
{
    public int CategoryId { get; set; }

    public int CategoryTypeId { get; set; }

    public long? UserId { get; set; }

    public string CategoryName { get; set; }

    public string CategoryCode { get; set; }

    public string Description { get; set; }

    public int? ParentCategoryId { get; set; }

    public bool IsActive { get; set; }

    public DateTime CreatedAt { get; set; }

    public DateTime UpdatedAt { get; set; }

    public virtual PhotoCategoryType CategoryType { get; set; }

    public virtual ICollection<PhotoAiclassificationSuggestion> PhotoAiclassificationSuggestions { get; set; } = new List<PhotoAiclassificationSuggestion>();

    public virtual ICollection<PhotoPhotoCategory> PhotoPhotoCategories { get; set; } = new List<PhotoPhotoCategory>();

    public virtual User User { get; set; }
}