// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Project_Photo.Models;

public partial class PhotoPhotoAlbum
{
    public long PhotoAlbumId { get; set; }

    public long PhotoId { get; set; }

    public long AlbumId { get; set; }

    public DateTime AddedAt { get; set; }

    public DateTime CreatedAt { get; set; }

    public virtual PhotoAlbum Album { get; set; }

    public virtual Photo Photo { get; set; }
}