// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Project_Photo.Models;

public partial class PhotoAlbum
{
    public long AlbumId { get; set; }

    public long UserId { get; set; }

    public string AlbumName { get; set; }

    public string Description { get; set; }

    public long? CoverPhotoId { get; set; }

    public bool IsPublic { get; set; }

    public bool IsDeleted { get; set; }

    public DateTime? DeletedAt { get; set; }

    public DateTime CreatedAt { get; set; }

    public DateTime UpdatedAt { get; set; }

    public virtual ICollection<PhotoPhotoAlbum> PhotoPhotoAlbums { get; set; } = new List<PhotoPhotoAlbum>();

    public virtual User User { get; set; }
}