// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Project_Photo.Models;

public partial class PhotoPhotoCategory
{
    public long PhotoId { get; set; }

    public int CategoryId { get; set; }

    public int SourceId { get; set; }

    public decimal? Confidence { get; set; }

    public long? AssignedBy { get; set; }

    public DateTime AssignedAt { get; set; }

    public DateTime CreatedAt { get; set; }

    public DateTime UpdatedAt { get; set; }

    public virtual PhotoCategory Category { get; set; }

    public virtual Photo Photo { get; set; }

    public virtual PhotoClassificationSource Source { get; set; }
}