// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Project_Photo.Models;

public partial class Photo
{
    public long PhotoId { get; set; }

    public long UserId { get; set; }

    public string FileName { get; set; }

    public string FileExtension { get; set; }

    public long FileSize { get; set; }

    public byte[] PhotoData { get; set; }

    public string Hash { get; set; }

    public DateTime UploadedAt { get; set; }

    public bool IsDeletedAt { get; set; }

    public DateTime? DeletedAt { get; set; }

    public DateTime CreatedAt { get; set; }

    public DateTime UpdatedAt { get; set; }

    public virtual ICollection<PhotoAiclassificationLog> PhotoAiclassificationLogs { get; set; } = new List<PhotoAiclassificationLog>();

    public virtual ICollection<PhotoLocation> PhotoLocations { get; set; } = new List<PhotoLocation>();

    public virtual ICollection<PhotoMetadatum> PhotoMetadata { get; set; } = new List<PhotoMetadatum>();

    public virtual ICollection<PhotoPhotoAlbum> PhotoPhotoAlbums { get; set; } = new List<PhotoPhotoAlbum>();

    public virtual PhotoPhotoCategory PhotoPhotoCategory { get; set; }

    public virtual ICollection<PhotoPhotoTag> PhotoPhotoTags { get; set; } = new List<PhotoPhotoTag>();

    public virtual ICollection<PhotoShare> PhotoShares { get; set; } = new List<PhotoShare>();

    public virtual ICollection<PhotoStorage> PhotoStorages { get; set; } = new List<PhotoStorage>();
}