// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Project_Photo.Models;

public partial class PhotoUserSubscription
{
    public long SubscriptionId { get; set; }

    public long UserId { get; set; }

    public int PlanId { get; set; }

    public string Status { get; set; }

    public string BilingCycle { get; set; }

    public DateTime StartDate { get; set; }

    public DateTime? EndDate { get; set; }

    public bool AutoRenew { get; set; }

    public DateTime? CancelledAt { get; set; }

    public string CancellationReason { get; set; }

    public long? PaymentMethodId { get; set; }

    public DateTime CreatedAt { get; set; }

    public DateTime UpdatedAt { get; set; }

    public virtual ICollection<PhotoSubscriptionHistory> PhotoSubscriptionHistories { get; set; } = new List<PhotoSubscriptionHistory>();

    public virtual ICollection<PhotoUserQuotaUsage> PhotoUserQuotaUsages { get; set; } = new List<PhotoUserQuotaUsage>();

    public virtual PhotoSubscriptionPlan Plan { get; set; }

    public virtual User User { get; set; }
}