// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Project_Photo.Models;

public partial class PhotoStorageProvider
{
    public int ProviderId { get; set; }

    public string ProviderCode { get; set; }

    public string ProviderName { get; set; }

    public string Description { get; set; }

    public bool IsActive { get; set; }

    public DateTime CreatedAt { get; set; }

    public DateTime UpdatedAt { get; set; }

    public virtual ICollection<PhotoStorage> PhotoStorages { get; set; } = new List<PhotoStorage>();
}