// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Project_Photo.Models;

public partial class Photographer
{
    public int PhotographerId { get; set; }

    public long UserId { get; set; }

    public string StudioType { get; set; }

    public string StudioName { get; set; }

    public string DisplayName { get; set; }

    public string BusinessAddress { get; set; }

    public string Description { get; set; }

    public int? YearsOfExperience { get; set; }

    public string Awards { get; set; }

    public string PortfolioUrl { get; set; }

    public string CertificateUrl { get; set; }

    public string IdcardUrl { get; set; }

    public string OtherDocuments { get; set; }

    public string WebsiteUrl { get; set; }

    public string FacebookUrl { get; set; }

    public string InstagramUrl { get; set; }

    public string VerificationStatus { get; set; }

    public DateTime? VerificationDate { get; set; }

    public long? VerifiedByUserId { get; set; }

    public string RejectionReason { get; set; }

    public bool IsApproved { get; set; }

    public DateTime? ApprovedAt { get; set; }

    public bool IsSuspended { get; set; }

    public string SuspendedReason { get; set; }

    public DateTime? SuspendedAt { get; set; }

    public decimal? AverageRating { get; set; }

    public int TotalReviews { get; set; }

    public int TotalBookings { get; set; }

    public bool IsActive { get; set; }

    public DateTime CreatedAt { get; set; }

    public DateTime UpdatedAt { get; set; }

    public virtual ICollection<AvailableSlot> AvailableSlots { get; set; } = new List<AvailableSlot>();

    public virtual ICollection<Booking> Bookings { get; set; } = new List<Booking>();

    public virtual ICollection<FavoritePhotographer> FavoritePhotographers { get; set; } = new List<FavoritePhotographer>();

    public virtual ICollection<PhotographerService> PhotographerServices { get; set; } = new List<PhotographerService>();

    public virtual ICollection<PhotographerSpecialty> PhotographerSpecialties { get; set; } = new List<PhotographerSpecialty>();

    public virtual ICollection<PhotographerVerificationHistory> PhotographerVerificationHistories { get; set; } = new List<PhotographerVerificationHistory>();

    public virtual ICollection<Review> Reviews { get; set; } = new List<Review>();

    public virtual ICollection<ServiceArea> ServiceAreas { get; set; } = new List<ServiceArea>();

    public virtual User User { get; set; }
}