// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Project_Photo.Models;

public partial class PhotoSubscriptionPlan
{
    public int PlanId { get; set; }

    public string PlanCode { get; set; }

    public string PlanName { get; set; }

    public string PlanDescription { get; set; }

    public int PlanLevel { get; set; }

    public int SystemId { get; set; }

    public decimal MonthlyPrice { get; set; }

    public bool IsActive { get; set; }

    public bool IsPublic { get; set; }

    public string Features { get; set; }

    public DateTime CreatedAt { get; set; }

    public DateTime UpdateAt { get; set; }

    public virtual ICollection<PhotoSubscriptionQuotum> PhotoSubscriptionQuota { get; set; } = new List<PhotoSubscriptionQuotum>();

    public virtual ICollection<PhotoUserSubscription> PhotoUserSubscriptions { get; set; } = new List<PhotoUserSubscription>();
}