// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Project_Photo.Models;

public partial class PhotoGeneralSetting
{
    public int SettingId { get; set; }

    public string SystemName { get; set; }

    public string SystemVersion { get; set; }

    public string WebSiteTitle { get; set; }

    public string WebSiteDescription { get; set; }

    public string WebSiteKeywords { get; set; }

    public string LogoUrl { get; set; }

    public string FaviconUrl { get; set; }

    public string CompanyName { get; set; }

    public string CompanyTaxId { get; set; }

    public string CompanyAddress { get; set; }

    public string CompanyPhone { get; set; }

    public string SupportEmail { get; set; }

    public DateTime CreatedAt { get; set; }

    public DateTime UpdatedAt { get; set; }
}