// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Project_Photo.Models;

public partial class PhotoSubscriptionHistory
{
    public long HistoryId { get; set; }

    public long UserId { get; set; }

    public long SubscriptionId { get; set; }

    public string ActionType { get; set; }

    public int? OldPlanId { get; set; }

    public int NewPlanId { get; set; }

    public string OldStatus { get; set; }

    public string NewStatus { get; set; }

    public string ChangeReason { get; set; }

    public decimal? Amount { get; set; }

    public decimal? ProrationAmount { get; set; }

    public DateTime EffectiveDate { get; set; }

    public string PerformedBy { get; set; }

    public string Ipaddress { get; set; }

    public DateTime CreatedAt { get; set; }

    public virtual PhotoUserSubscription Subscription { get; set; }

    public virtual User User { get; set; }
}