// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Project_Photo.Models;

public partial class PhotoSecuritySetting
{
    public int SettingId { get; set; }

    public int PasswordMinLength { get; set; }

    public bool PasswordRequireUppercase { get; set; }

    public bool PasswordRequireLowercase { get; set; }

    public bool PasswordRequireDigit { get; set; }

    public bool PasswordRequireSpecialChar { get; set; }

    public int LoginFailedLockCount { get; set; }

    public int LoginLockDuration { get; set; }

    public int SessionTimeout { get; set; }

    public bool TwoFactorAuthRequired { get; set; }

    public DateTime CreatedAt { get; set; }

    public DateTime UpdatedAt { get; set; }
}