// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Project_Photo.Models;

public partial class PhotoQuotaType
{
    public int QuotaTypeId { get; set; }

    public string QuotaTypeCode { get; set; }

    public string QuotaTypeName { get; set; }

    public string QuotaUnit { get; set; }

    public string Description { get; set; }

    public int SystemId { get; set; }

    public string ResetPeriod { get; set; }

    public bool IsActive { get; set; }

    public DateTime CreatedAt { get; set; }

    public DateTime UpdatedAt { get; set; }

    public virtual ICollection<PhotoSubscriptionQuotum> PhotoSubscriptionQuota { get; set; } = new List<PhotoSubscriptionQuotum>();

    public virtual ICollection<PhotoUserQuotaUsage> PhotoUserQuotaUsages { get; set; } = new List<PhotoUserQuotaUsage>();
}