// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Project_Photo.Models;

public partial class PhotoAiclassificationSuggestion
{
    public long SuggestionId { get; set; }

    public long LogId { get; set; }

    public int CategoryId { get; set; }

    public decimal Confidence { get; set; }

    public bool IsAdopted { get; set; }

    public DateTime CreatedAt { get; set; }

    public virtual PhotoCategory Category { get; set; }

    public virtual PhotoAiclassificationLog Log { get; set; }
}