// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Project_Photo.Models;

public partial class PhotoMaintenanceSetting
{
    public int SettingId { get; set; }

    public bool IsMaintenanceMode { get; set; }

    public string MaintenanceMessage { get; set; }

    public DateTime? MaintenanceStartTime { get; set; }

    public DateTime? MaintenanceEndTime { get; set; }

    public string AllowedUserIds { get; set; }

    public DateTime CreatedAt { get; set; }

    public DateTime UpdatedAt { get; set; }
}