// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Project_Photo.Models;

public partial class PhotoSubscriptionQuotum
{
    public int QuotaId { get; set; }

    public int PlanId { get; set; }

    public int QuotaTypeId { get; set; }

    public long QuotaValue { get; set; }

    public int? ResetDay { get; set; }

    public bool IsActive { get; set; }

    public DateTime CreatedAt { get; set; }

    public DateTime UpdatedAt { get; set; }

    public virtual PhotoSubscriptionPlan Plan { get; set; }

    public virtual PhotoQuotaType QuotaType { get; set; }
}