// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Project_Photo.Models;

public partial class PhotoStorage
{
    public long StorageId { get; set; }

    public long PhotoId { get; set; }

    public int ProviderId { get; set; }

    public string StoragePath { get; set; }

    public string BucketName { get; set; }

    public string Region { get; set; }

    public string AccessUrl { get; set; }

    public bool IsPrimary { get; set; }

    public DateTime CreatedAt { get; set; }

    public DateTime UpdatedAt { get; set; }

    public virtual Photo Photo { get; set; }

    public virtual PhotoStorageProvider Provider { get; set; }
}