// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Project_Photo.Models;

public partial class PhotoShare
{
    public long ShareId { get; set; }

    public long PhotoId { get; set; }

    public long UserId { get; set; }

    public string ShareToken { get; set; }

    public string ShareType { get; set; }

    public string Password { get; set; }

    public DateTime? ExpiresAt { get; set; }

    public int ViewCount { get; set; }

    public int DownloadCount { get; set; }

    public bool IsActive { get; set; }

    public DateTime CreatedAt { get; set; }

    public DateTime UpdatedAt { get; set; }

    public virtual Photo Photo { get; set; }

    public virtual User User { get; set; }
}