// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Project_Photo.Models;

public partial class PhotoThirdPartyServiceType
{
    public int ServiceTypeId { get; set; }

    public string ServiceCode { get; set; }

    public string ServiceName { get; set; }

    public string Description { get; set; }

    public bool IsActive { get; set; }

    public DateTime CreatedAt { get; set; }

    public DateTime UpdatedAt { get; set; }

    public virtual ICollection<PhotoThirdPartyConfig> PhotoThirdPartyConfigs { get; set; } = new List<PhotoThirdPartyConfig>();
}