// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Project_Photo.Models;

public partial class PhotoThirdPartyConfig
{
    public int ConfigId { get; set; }

    public int ServiceTypeId { get; set; }

    public string ProviderName { get; set; }

    public string Apikey { get; set; }

    public string Apisecret { get; set; }

    public string EndpointUrl { get; set; }

    public string ConfigJson { get; set; }

    public bool IsActive { get; set; }

    public bool IsPrimary { get; set; }

    public DateTime CreatedAt { get; set; }

    public DateTime UpdatedAt { get; set; }

    public virtual PhotoThirdPartyServiceType ServiceType { get; set; }
}