// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Project_Photo.Models;

public partial class PhotoUploadLimitSetting
{
    public int SettingId { get; set; }

    public int MaxFileSizeMb { get; set; }

    public int MaxBatchUploadCount { get; set; }

    public string AllowedExtensions { get; set; }

    public int FreeUserStorageGb { get; set; }

    public DateTime CreatedAt { get; set; }

    public DateTime UpdatedAt { get; set; }
}