// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Project_Photo.Models;

public partial class PhotoUserQuotaUsage
{
    public long UsageId { get; set; }

    public long UserId { get; set; }

    public long SubscriptionId { get; set; }

    public int QuotaTypeId { get; set; }

    public long UsedAmount { get; set; }

    public DateTime PeriodStartDate { get; set; }

    public DateTime CreatedAt { get; set; }

    public DateTime UpdatedAt { get; set; }

    public virtual PhotoQuotaType QuotaType { get; set; }

    public virtual PhotoUserSubscription Subscription { get; set; }

    public virtual User User { get; set; }
}