// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Project_Photo.Models;

public partial class PhotoMetadatum
{
    public long PhotoMetadata { get; set; }

    public long PhotoId { get; set; }

    public string CameraMake { get; set; }

    public string CameraModel { get; set; }

    public DateTime? DateTaken { get; set; }

    public decimal? Gpslatitude { get; set; }

    public decimal? Gpslongitude { get; set; }

    public DateTime CreatedAt { get; set; }

    public DateTime UpdatedAt { get; set; }

    public virtual Photo Photo { get; set; }
}