// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Project_Photo.Models;

public partial class PickupConvenienceStore
{
    public int ConvenienceStoreId { get; set; }

    public long UserId { get; set; }

    public string RecipientName { get; set; }

    public string PhoneNumber { get; set; }

    public string ConvenienceStoreCode { get; set; }

    public string ConvenienceStoreName { get; set; }

    public bool IsDefault { get; set; }

    public DateTime CreatedAt { get; set; }

    public DateTime UpdatedAt { get; set; }

    public virtual ICollection<BuyerDetail> BuyerDetails { get; set; } = new List<BuyerDetail>();

    public virtual User User { get; set; }
}