// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Project_Photo.Models;

public partial class Playlist
{
    public int PlaylistId { get; set; }

    public long UserId { get; set; }

    public string Title { get; set; }

    public string Description { get; set; }

    public bool Privacy { get; set; }

    public int VideoCount { get; set; }

    public DateTime CreatedAt { get; set; }

    public DateTime UpdateAt { get; set; }

    public virtual User User { get; set; }
}