// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Project_Photo.Models;

public partial class PlaylistVideo
{
    public int PlaylistId { get; set; }

    public int VideoId { get; set; }

    public int Position { get; set; }

    public DateTime CreatedAt { get; set; }

    public DateTime UpdateAt { get; set; }

    public virtual Playlist Playlist { get; set; }

    public virtual Video Video { get; set; }
}