// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Project_Photo.Models;

public partial class Post
{
    public int PostId { get; set; }

    public long UserId { get; set; }

    public string PostType { get; set; }

    public int? PostTypeId { get; set; }

    public string PostContent { get; set; }

    public string Status { get; set; }

    public int? ParentPostId { get; set; }

    public DateTime CreatedAt { get; set; }

    public DateTime UpdatedAt { get; set; }

    public DateTime? DeletedAt { get; set; }

    public virtual ICollection<Post> InverseParentPost { get; set; } = new List<Post>();

    public virtual Post ParentPost { get; set; }
}