// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Project_Photo.Models;

public partial class PostShare
{
    public int ShareId { get; set; }

    public long UserId { get; set; }

    public int PostId { get; set; }

    public DateTime CreatedAt { get; set; }

    public virtual Post Post { get; set; }

    public virtual User User { get; set; }
}