// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Project_Photo.Models;

public partial class PostReport
{
    public int ReportId { get; set; }

    public int PostId { get; set; }

    public long ReporterId { get; set; }

    public long ReportedId { get; set; }

    public int ReasonId { get; set; }

    public string ReporterDescription { get; set; }

    public string Status { get; set; }

    public DateTime? ReviewedAt { get; set; }

    public string ReviewerDescription { get; set; }

    public DateTime CreatedAt { get; set; }

    public DateTime UpdateAt { get; set; }

    public DateTime? DeleteAt { get; set; }

    public virtual ReportReason Reason { get; set; }

    public virtual User Reported { get; set; }

    public virtual User Reporter { get; set; }
}