// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Project_Photo.Models;

public partial class ProductImage
{
    public int ProductImageId { get; set; }

    public long ProductId { get; set; }

    public string ImageUrl { get; set; }

    public bool IsMainImage { get; set; }

    public int DisplayOrder { get; set; }

    public DateTime CreatedAt { get; set; }

    public DateTime UpdatedAt { get; set; }

    public virtual Product Product { get; set; }
}