// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Project_Photo.Models;

public partial class ProductPropertyDetail
{
    public int PropertyDetailsId { get; set; }

    public int PropertyId { get; set; }

    public string OptionValue { get; set; }

    public DateTime CreatedAt { get; set; }

    public DateTime UpdatedAt { get; set; }

    public virtual ProductProperty Property { get; set; }

    public virtual ICollection<SpecOptionMapping> SpecOptionMappings { get; set; } = new List<SpecOptionMapping>();
}