// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Project_Photo.Models;

public partial class ProductAudit
{
    public int ProductAuditId { get; set; }

    public long ProductId { get; set; }

    public long AdministratorUserId { get; set; }

    public string Status { get; set; }

    public string VerificationReasons { get; set; }

    public DateTime AuditTime { get; set; }

    public DateTime CreatedAt { get; set; }

    public DateTime UpdatedAt { get; set; }

    public virtual Product Product { get; set; }
}