// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Project_Photo.Models;

public partial class ProductShippingOption
{
    public int ShippingOptionId { get; set; }

    public long ProductId { get; set; }

    public string ShippingMethod { get; set; }

    public decimal Freight { get; set; }

    public string CombineRule { get; set; }

    public DateTime CreatedAt { get; set; }

    public DateTime UpdatedAt { get; set; }

    public virtual Product Product { get; set; }
}