// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Project_Photo.Models;

public partial class ProductProperty
{
    public int PropertyId { get; set; }

    public long ProductId { get; set; }

    public string PropertyName { get; set; }

    public DateTime CreatedAt { get; set; }

    public DateTime UpdatedAt { get; set; }

    public virtual Product Product { get; set; }

    public virtual ICollection<ProductPropertyDetail> ProductPropertyDetails { get; set; } = new List<ProductPropertyDetail>();
}