// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Project_Photo.Models;

public partial class RefundRequest
{
    public long RefundRequestId { get; set; }

    public long UserId { get; set; }

    public long TransactionId { get; set; }

    public long? RefundTransactionId { get; set; }

    public string RequestNo { get; set; }

    public decimal RefundAmount { get; set; }

    public string RefundReason { get; set; }

    public long? RefundBankAccountId { get; set; }

    public string Status { get; set; }

    public long? ReviewedBy { get; set; }

    public DateTime? ReviewedAt { get; set; }

    public string ReviewNote { get; set; }

    public DateTime? CompletedAt { get; set; }

    public DateTime CreatedAt { get; set; }

    public DateTime UpdatedAt { get; set; }

    public virtual PaymentTransaction Transaction { get; set; }

    public virtual User User { get; set; }
}