// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Project_Photo.Models;

public partial class Report1
{
    public int ReportId { get; set; }

    public string ReportedType { get; set; }

    public long ReporterId { get; set; }

    public int ReportedId { get; set; }

    public string Description { get; set; }

    public string Status { get; set; }

    public DateTime CreatedAt { get; set; }

    public DateTime UpdateAt { get; set; }

    public virtual ICollection<AdminAction1> AdminAction1s { get; set; } = new List<AdminAction1>();

    public virtual User Reporter { get; set; }
}