// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Project_Photo.Models;

public partial class Report
{
    public int ReportId { get; set; }

    public long ReporterUserId { get; set; }

    public long? ReportedProductId { get; set; }

    public long? ReportedSellerUserId { get; set; }

    public string ReportType { get; set; }

    public string ReportingReasons { get; set; }

    public string Status { get; set; }

    public int? ProductAuditId { get; set; }

    public DateTime CreatedAt { get; set; }

    public DateTime UpdatedAt { get; set; }

    public virtual Product ReportedProduct { get; set; }

    public virtual User ReportedSellerUser { get; set; }

    public virtual User ReporterUser { get; set; }
}