// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Project_Photo.Models;

public partial class ReportReason
{
    public int ReasonId { get; set; }

    public string ReasonType { get; set; }

    public string Description { get; set; }

    public virtual ICollection<PostReport> PostReports { get; set; } = new List<PostReport>();
}