// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Project_Photo.Models;

public partial class Review
{
    public int ReviewId { get; set; }

    public int OrderDetailsId { get; set; }

    public long ReviewerUserId { get; set; }

    public long RevieweeUserId { get; set; }

    public string ReviewType { get; set; }

    public byte Rating { get; set; }

    public string ReviewContent { get; set; }

    public DateTime CreatedAt { get; set; }

    public DateTime UpdatedAt { get; set; }

    public virtual OrderDetail OrderDetails { get; set; }

    public virtual ICollection<ReviewPhoto> ReviewPhotos { get; set; } = new List<ReviewPhoto>();
}