// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Project_Photo.Models;

public partial class Review
{
    public int ReviewId { get; set; }

    public int BookingId { get; set; }

    public long UserId { get; set; }

    public int PhotographerId { get; set; }

    public int OverallRating { get; set; }

    public int? ProfessionalismRating { get; set; }

    public int? CommunicationRating { get; set; }

    public int? QualityRating { get; set; }

    public int? ValueRating { get; set; }

    public string ReviewTitle { get; set; }

    public string ReviewContent { get; set; }

    public string ReviewPhotos { get; set; }

    public string PhotographerReply { get; set; }

    public DateTime? RepliedAt { get; set; }

    public bool IsVerified { get; set; }

    public bool IsHidden { get; set; }

    public int ReportCount { get; set; }

    public DateTime CreatedAt { get; set; }

    public virtual Booking Booking { get; set; }

    public virtual Photographer Photographer { get; set; }

    public virtual User User { get; set; }
}