// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Project_Photo.Models;

public partial class SellerAuditHistory
{
    public int SellerAuditId { get; set; }

    public long SellerUserId { get; set; }

    public long AdministratorUserId { get; set; }

    public string AuditStatus { get; set; }

    public string VerificationReasons { get; set; }

    public DateTime AuditTime { get; set; }

    public DateTime CreatedAt { get; set; }

    public virtual User AdministratorUser { get; set; }

    public virtual User SellerUser { get; set; }
}