// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Project_Photo.Models;

public partial class SellerCategory
{
    public int SellerCategoryId { get; set; }

    public long UserId { get; set; }

    public string CategoryName { get; set; }

    public bool IsVisible { get; set; }

    public DateTime CreatedAt { get; set; }

    public DateTime UpdatedAt { get; set; }

    public virtual ICollection<ProductSellerCategoryMappin> ProductSellerCategoryMappins { get; set; } = new List<ProductSellerCategoryMappin>();
}