// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Project_Photo.Models;

public partial class SellerDetail
{
    public int SellerDetailsId { get; set; }

    public long SellerUserId { get; set; }

    public string IdcardImage { get; set; }

    public long BankAccountId { get; set; }

    public decimal WalletBalance { get; set; }

    public string ReviewStatus { get; set; }

    public string VerificationReasons { get; set; }

    public DateTime? AuditTime { get; set; }

    public long AdministratorUserId { get; set; }

    public DateTime CreatedAt { get; set; }

    public DateTime UpdatedAt { get; set; }
}