// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Project_Photo.Models;

public partial class ServiceType
{
    public int ServiceTypeId { get; set; }

    public string ServiceName { get; set; }

    public string Description { get; set; }

    public string IconUrl { get; set; }

    public int DisplayOrder { get; set; }

    public bool IsActive { get; set; }

    public virtual ICollection<PhotographerService> PhotographerServices { get; set; } = new List<PhotographerService>();
}