// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Project_Photo.Models;

public partial class ShoppingCart
{
    public int ShoppingCartId { get; set; }

    public long UserId { get; set; }

    public int SpecificationId { get; set; }

    public int Quantity { get; set; }

    public DateTime CreatedAt { get; set; }

    public DateTime UpdatedAt { get; set; }

    public virtual ProductSpecification Specification { get; set; }

    public virtual User User { get; set; }
}