// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Project_Photo.Models;

public partial class SpecOptionMapping
{
    public int SpecOptionMappingId { get; set; }

    public int SpecificationId { get; set; }

    public int PropertyDetailsId { get; set; }

    public virtual ProductPropertyDetail PropertyDetails { get; set; }

    public virtual ProductSpecification Specification { get; set; }
}