// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Project_Photo.Models;

public partial class StoreBasicInformation
{
    public int StoreId { get; set; }

    public long UserId { get; set; }

    public string StoreName { get; set; }

    public string StoreDescription { get; set; }

    public string StoreImageUrl { get; set; }

    public DateTime CreatedAt { get; set; }

    public DateTime UpdatedAt { get; set; }
}