// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Project_Photo.Models;

public partial class TransactionStatusType
{
    public int StatusTypeId { get; set; }

    public string StatusCode { get; set; }

    public string StatusName { get; set; }

    public string Description { get; set; }

    public bool IsFinal { get; set; }

    public bool IsSuccess { get; set; }

    public DateTime CreatedAt { get; set; }

    public DateTime UpdatedAt { get; set; }

    public virtual ICollection<TransactionStatusLog> TransactionStatusLogs { get; set; } = new List<TransactionStatusLog>();
}