// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Project_Photo.Models;

public partial class TransactionStatusLog
{
    public long StatusLogId { get; set; }

    public long TransactionId { get; set; }

    public int StatusTypeId { get; set; }

    public string StatusMessage { get; set; }

    public string GatewayResponse { get; set; }

    public string ErrorCode { get; set; }

    public string ErrorMessage { get; set; }

    public DateTime CreatedAt { get; set; }

    public virtual TransactionStatusType StatusType { get; set; }

    public virtual PaymentTransaction Transaction { get; set; }
}