// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Project_Photo.Models;

public partial class UserSecurityStatus
{
    public long UserId { get; set; }

    public int FailedLoginAttempts { get; set; }

    public DateTime? LastFailedLoginAt { get; set; }

    public bool IsLocked { get; set; }

    public DateTime? LockedAt { get; set; }

    public DateTime? LockedUntil { get; set; }

    public string LockedReason { get; set; }

    public string LockedBy { get; set; }

    public DateTime? UnlockedAt { get; set; }

    public DateTime UpdatedAt { get; set; }

    public virtual User User { get; set; }
}