// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Project_Photo.Models;

public partial class UserNotificationPreference
{
    public long PreferenceId { get; set; }

    public long UserId { get; set; }

    public bool EmailNotification { get; set; }

    public bool Smsnotification { get; set; }

    public bool PushNotification { get; set; }

    public bool MarketingEmail { get; set; }

    public bool OrderUpdate { get; set; }

    public bool PromotionAlert { get; set; }

    public bool SystemAnnouncement { get; set; }

    public DateTime CreatedAt { get; set; }

    public DateTime UpdatedAt { get; set; }

    public virtual User User { get; set; }
}