// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Project_Photo.Models;

public partial class UserLog
{
    public long LogId { get; set; }

    public long? UserId { get; set; }

    public string Status { get; set; }

    public string ActionType { get; set; }

    public string ActionCategory { get; set; }

    public string ActionDescription { get; set; }

    public string TargetType { get; set; }

    public long? TargetId { get; set; }

    public string OldValue { get; set; }

    public string NewValue { get; set; }

    public string Ipaddress { get; set; }

    public string UserAgent { get; set; }

    public string DeviceType { get; set; }

    public string SystemName { get; set; }

    public string Severity { get; set; }

    public string ErrorMessage { get; set; }

    public int? ExcutionTime { get; set; }

    public string PerformedBy { get; set; }

    public DateTime CreatedAt { get; set; }

    public virtual User User { get; set; }
}