// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Project_Photo.Models;

public partial class UserRolePermission
{
    public long RolePermissionId { get; set; }

    public int RoleTypeId { get; set; }

    public int PermissionId { get; set; }

    public bool CanGrant { get; set; }

    public DateTime CreatedAt { get; set; }

    public DateTime UpdatedAt { get; set; }

    public virtual UserPermission Permission { get; set; }

    public virtual UserRoleType RoleType { get; set; }
}