// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Project_Photo.Models;

public partial class UserVerification
{
    public long VerificationId { get; set; }

    public long UserId { get; set; }

    public int VerificationTypeId { get; set; }

    public string VerificationCode { get; set; }

    public string VerificationToken { get; set; }

    public string SentTo { get; set; }

    public string Purpose { get; set; }

    public DateTime RequestedAt { get; set; }

    public DateTime ExpiredAt { get; set; }

    public bool IsVerified { get; set; }

    public DateTime? VerifiedAt { get; set; }

    public bool IsUsed { get; set; }

    public string Ipaddress { get; set; }

    public int FailedAttempts { get; set; }

    public DateTime CreatedAt { get; set; }

    public DateTime UpdatedAt { get; set; }

    public virtual User User { get; set; }

    public virtual UserVerificationType VerificationType { get; set; }
}