// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Project_Photo.Models;

public partial class UserSystemModule
{
    public int SystemId { get; set; }

    public string SystemCode { get; set; }

    public string SystemName { get; set; }

    public string SystemDescription { get; set; }

    public bool IsActive { get; set; }

    public DateTime CreatedAt { get; set; }

    public DateTime UpdatedAt { get; set; }

    public virtual ICollection<FrequentlyAskedQuestion> FrequentlyAskedQuestions { get; set; } = new List<FrequentlyAskedQuestion>();

    public virtual ICollection<NotificationTemplate> NotificationTemplates { get; set; } = new List<NotificationTemplate>();

    public virtual ICollection<PhotoQuotaType> PhotoQuotaTypes { get; set; } = new List<PhotoQuotaType>();

    public virtual ICollection<PhotoSubscriptionPlan> PhotoSubscriptionPlans { get; set; } = new List<PhotoSubscriptionPlan>();

    public virtual ICollection<UserPermission> UserPermissions { get; set; } = new List<UserPermission>();

    public virtual ICollection<UserRoleType> UserRoleTypes { get; set; } = new List<UserRoleType>();
}