// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Project_Photo.Models;

public partial class UserBankAccount
{
    public long BankAccountId { get; set; }

    public long UserId { get; set; }

    public int BankId { get; set; }

    public int? BranchId { get; set; }

    public string AccountNumber { get; set; }

    public string AccountName { get; set; }

    public string AccountType { get; set; }

    public bool IsDefault { get; set; }

    public bool IsVerified { get; set; }

    public DateTime? VerifiedAt { get; set; }

    public bool IsActive { get; set; }

    public DateTime CreatedAt { get; set; }

    public DateTime UpdatedAt { get; set; }

    public virtual Bank Bank { get; set; }

    public virtual BankBranch Branch { get; set; }

    public virtual User User { get; set; }
}