// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Project_Photo.Models;

public partial class UserPermission
{
    public int PermissionId { get; set; }

    public string PermissionCode { get; set; }

    public string PermissionName { get; set; }

    public string PermissionDescription { get; set; }

    public int CategoryId { get; set; }

    public int SystemId { get; set; }

    public int? ParentPermissionId { get; set; }

    public bool IsActive { get; set; }

    public virtual UserPermissionCategory Category { get; set; }

    public virtual UserSystemModule System { get; set; }

    public virtual ICollection<UserRolePermission> UserRolePermissions { get; set; } = new List<UserRolePermission>();
}