// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Project_Photo.Models;

public partial class UserVerificationType
{
    public int VerificationTypeId { get; set; }

    public string VerificationTypeName { get; set; }

    public DateTime CreatedAt { get; set; }

    public DateTime UpdatedAt { get; set; }

    public virtual ICollection<UserVerification> UserVerifications { get; set; } = new List<UserVerification>();
}