// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Project_Photo.Models;

public partial class WalletTransaction
{
    public int TransactionId { get; set; }

    public long SellerUserId { get; set; }

    public decimal Amount { get; set; }

    public string TransactionType { get; set; }

    public string TransactionStatus { get; set; }

    public int? OrderId { get; set; }

    public int? PayoutBatchId { get; set; }

    public decimal CurrentBalance { get; set; }

    public DateTime CreatedAt { get; set; }

    public DateTime UpdatedAt { get; set; }
}